-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_replies.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE IF NOT EXISTS /*_*/cs_replies (
  cst_r_reply_page_id INT UNSIGNED NOT NULL,
  cst_r_comment_page_id INT UNSIGNED NOT NULL,
  PRIMARY KEY(cst_r_reply_page_id)
) /*$wgDBTableOptions*/;
-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: cs_comments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE IF NOT EXISTS /*_*/cs_comments (
  cst_c_comment_page_id INT UNSIGNED NOT NULL,
  cst_c_assoc_page_id INT UNSIGNED NOT NULL,
  cst_c_comment_title VARBINARY(255) NOT NULL,
  cst_c_block_name VARBINARY(255) DEFAULT NULL,
  PRIMARY KEY(cst_c_comment_page_id)
) /*$wgDBTableOptions*/;
