<?php

$wgLBFactoryConf = [
	'class' => 'LBFactoryMulti',
	'sectionsByDB' => [
		'altversewiki' => 'c3',
		'anotheredenwiki' => 'c3',
		'centralauth' => 'c1',
		'concordancewiki' => 'c3',
		'dreamversewiki' => 'c3',
		'hispanowiki' => 'c3',
		'mhglobal' => 'c1',
		'nbdbwiki' => 'c3',
		'nonbinarywiki' => 'c3',
		'onepiecewiki' => 'c3',
		'onepiecebountyrushwiki' => 'c3',
		'openhatchwiki' => 'c3',
		'privadowiki' => 'c3',
		'proxybotwiki' => 'c3',
		'rotompediawiki' => 'c3',
		'staffwiki' => 'c3',
 		'testwiki' => 'c3',
		'ucroniaswiki' => 'c3',
		
		// large wikis
		'buswiki' => 'c3',
		'pathofexilewiki' => 'c3',
		'tmewiki' => 'c3',
		'vsrecommendedgameswiki' => 'c3',
		'animatedfeetwiki' => 'c3',
		'crappygameswiki' => 'c3',
		'anglishwiki' => 'c3',
		'trollpastawiki' => 'c3',
		'poserdazfreebieswiki' => 'c3',
		'nltramswiki' => 'c3',
		'beidipediawiki' => 'c3',
		'nilamwikiubzx217c40wiki' => 'c3',
		'bluepageswiki' => 'c3',
		'awfulmovieswiki' => 'c3',
		'uncyclopediawiki' => 'c3',
		'tolololpediawiki' => 'c3',
		'platprojectwiki' => 'c3',
		'trollpastawikiwiki' => 'c3',
		'ansaikuropediawiki' => 'c3',
		'pluspiwiki' => 'c3',
		'csydeswiki' => 'c3',
		'atrociousyoutuberswiki' => 'c3',
		'anterrawiki' => 'c3',
		'jayuvandalwiki' => 'c3',
		'ciptamediawiki' => 'c3',
		'bpwiki' => 'c3',
		'terribletvshowswiki' => 'c3',
		'osaindexwiki' => 'c3',
		'newusopediawiki' => 'c3',
		'mc2wiki' => 'c3',
		'jawp2chwiki' => 'c3',
		'sumroletaericwiki' => 'c3',
		'sidemwiki' => 'c3',
		'ranchstorywiki' => 'c3',
		'maiasongcontestwiki' => 'c3',
		'awesomegameswiki' => 'c3',
		'animebathswiki' => 'c3',
		'americangirldollswiki' => 'c3',
		'schattenvonskeloswiki' => 'c3',
		's23wiki' => 'c3',
		'libertygamewiki' => 'c3',
		'healthyfandomsandandhatedomwiki' => 'c3',
		'gyaanipediawiki' => 'c3',
		'bigforestwiki' => 'c3',
		'2b2twiki' => 'c3',
		'simswiki' => 'c3',
		'frikipediawiki' => 'c3',
		'uncyclomirrorwiki' => 'c3',
		'baobabarchiveswiki' => 'c3',
		'zhdelwiki' => 'c3',
		'allthetropeswiki' => 'c3',
		'nonciclopediawiki' => 'c3',
		'toxicfandomsandhatedomswiki' => 'c3',
		'nonsensopediawiki' => 'c3',
 	],
	'sectionLoads' => [
		'DEFAULT' => [
			'db4' => 1,
		],
		'c1' => [
			'db4' => 1,
		],
		'c3' => [
 			'db6' => 1,
 		],
	],
	'serverTemplate' => [
		'dbname' => $wgDBname,
		'user' => $wgDBuser,
		'password' => $wgDBpassword,
		'type' => 'mysql',
		'flags' => DBO_SSL | DBO_COMPRESS,
		'sslCertPath' => '/etc/ssl/certs/wildcard.miraheze.org.crt',
		'sslKeyPath' => '/etc/ssl/private/wildcard.miraheze.org.key',
	],
	'hostsByName' => [
		'db4' => 'db4.miraheze.org',
		'db6' => 'db6.miraheze.org',
	],
	'externalLoads' => [
		'echo' => [
			'db4' => 1, // should echo c1
		],
	],
	'readOnlyBySection' => [
		'DEFAULT' => 'Maintenance ongoing on the database server.',
		'c1' => 'Maintenance ongoing on the database server.',
		'c3' => 'Maintenance ongoing on the database server.',
	],
];
