<?php
## This file is generated by mergeMessageFileList.php. Do not edit it directly.

if ( defined( 'MW_NO_EXTENSION_MESSAGES' ) ) return;

$wgExtensionMessagesFiles = array (
  'AbuseFilterAliases' => "$IP/extensions/AbuseFilter/AbuseFilter.alias.php",
  'BabelMagic' => "$IP/extensions/Babel/Babel.i18n.magic.php",
  'BetaFeaturesAlias' => "$IP/extensions/BetaFeatures/BetaFeatures.alias.php",
  'SpecialCentralAuthAliases' => "$IP/extensions/CentralAuth/CentralAuth.alias.php",
  'SpecialCentralAuthAliasesNoTranslate' => "$IP/extensions/CentralAuth/CentralAuth.notranslate-alias.php",
  'CheckUserAliases' => "$IP/extensions/CheckUser/CheckUser.alias.php",
  'CiteThisPageAliases' => "$IP/extensions/CiteThisPage/CiteThisPage.alias.php",
  'ConfirmEditAlias' => "$IP/extensions/ConfirmEdit/ConfirmEdit.alias.php",
  'DisambiguatorAlias' => "$IP/extensions/Disambiguator/Disambiguator.i18n.alias.php",
  'DisambiguatorMagic' => "$IP/extensions/Disambiguator/Disambiguator.i18n.magic.php",
  'EchoAliases' => "$IP/extensions/Echo/Echo.alias.php",
  'GadgetsAlias' => "$IP/extensions/Gadgets/Gadgets.alias.php",
  'GadgetsNamespaces' => "$IP/extensions/Gadgets/Gadgets.namespaces.php",
  'GlobalBlockingAlias' => "$IP/extensions/GlobalBlocking/GlobalBlocking.alias.php",
  'InterwikiAlias' => "$IP/extensions/Interwiki/Interwiki.alias.php",
  'MassMessageAlias' => "$IP/extensions/MassMessage/MassMessage.alias.php",
  'MassMessageMagic' => "$IP/extensions/MassMessage/MassMessage.i18n.magic.php",
  'MathAlias' => "$IP/extensions/Math/Math.alias.php",
  'MathAliasNoTranslate' => "$IP/extensions/Math/Math.alias.noTranslate.php",
  'NukeAlias' => "$IP/extensions/Nuke/Nuke.alias.php",
  'OATHAuthAlias' => "$IP/extensions/OATHAuth/OATHAuth.alias.php",
  'MWOAuthAliases' => "$IP/extensions/OAuth/frontend/language/MWOAuth.alias.php",
  'ParserFunctionsMagic' => "$IP/extensions/ParserFunctions/ParserFunctions.i18n.magic.php",
  'RenameuserAliases' => "$IP/extensions/Renameuser/Renameuser.alias.php",
  'SiteMatrixAlias' => "$IP/extensions/SiteMatrix/SiteMatrix.alias.php",
  'SiteMatrixMagic' => "$IP/extensions/SiteMatrix/SiteMatrix.i18n.magic.php",
  'ThanksAlias' => "$IP/extensions/Thanks/Thanks.alias.php",
  'ArticleFeedbackv5Alias' => "$IP/extensions/ArticleFeedbackv5/ArticleFeedbackv5.alias.php",
  'ArticleRatingsAlias' => "$IP/extensions/ArticleRatings/ArticleRatings.alias.php",
  'BlogPageAlias' => "$IP/extensions/BlogPage/BlogPage.alias.php",
  'BlogPageNamespaces' => "$IP/extensions/BlogPage/BlogPage.namespaces.php",
  'CategoryTreeAlias' => "$IP/extensions/CategoryTree/CategoryTree.alias.php",
  'CategoryTreeMagic' => "$IP/extensions/CategoryTree/CategoryTree.i18n.magic.php",
  'CentralNoticeAliases' => "$IP/extensions/CentralNotice/CentralNotice.alias.php",
  'CommentsAliases' => "$IP/extensions/Comments/Comments.alias.php",
  'CommentsMagic' => "$IP/extensions/Comments/Comments.i18n.magic.php",
  'NumberOfCommentsMagic' => "$IP/extensions/Comments/Comments.i18n.magic.php",
  'ContactPageAliases' => "$IP/extensions/ContactPage/ContactPage.alias.php",
  'DPLforumMagic' => "$IP/extensions/DPLForum/DPLforum.i18n.magic.php",
  'DPLforumNamespaces' => "$IP/extensions/DPLForum/DPLforum.namespaces.php",
  'DynamicPageListMagic' => "$IP/extensions/DynamicPageList3/DynamicPageList.i18n.magic.php",
  'EditcountAliases' => "$IP/extensions/Editcount/Editcount.alias.php",
  'EducationProgramAlias' => "$IP/extensions/EducationProgram/EducationProgram.i18n.alias.php",
  'EPNamespaces' => "$IP/extensions/EducationProgram/EducationProgram.i18n.ns.php",
  'EventLoggingNamespaces' => "$IP/extensions/EventLogging/EventLogging.namespaces.php",
  'FlowNamespaces' => "$IP/extensions/Flow/Flow.namespaces.php",
  'FlowAlias' => "$IP/extensions/Flow/Flow.alias.php",
  'GraphAliases' => "$IP/extensions/Graph/Graph.alias.php",
  'HeaderTabsMagic' => "$IP/extensions/HeaderTabs/HeaderTabs.i18n.magic.php",
  'JosaMagic' => "$IP/extensions/Josa/Josa.i18n.magic.php",
  'MediaWikiChatAlias' => "$IP/extensions/MediaWikiChat/MediaWikiChat.alias.php",
  'MobileFrontendAlias' => "$IP/extensions/MobileFrontend/MobileFrontend.alias.php",
  'ModerationAlias' => "$IP/extensions/Moderation/Moderation.alias.php",
  'NewestPagesAlias' => "$IP/extensions/NewestPages/NewestPages.alias.php",
  'NewsletterAlias' => "$IP/extensions/Newsletter/Newsletter.alias.php",
  'PagedTiffHandlerMagic' => "$IP/extensions/PagedTiffHandler/PagedTiffHandler.i18n.magic.php",
  'PageTriageAlias' => "$IP/extensions/PageTriage/PageTriage.alias.php",
  'ProofreadPageAlias' => "$IP/extensions/ProofreadPage/ProofreadPage.alias.php",
  'ProtectSiteAliases' => "$IP/extensions/ProtectSite/ProtectSite.alias.php",
  'RelatedArticlesMagic' => "$IP/extensions/RelatedArticles/RelatedArticles.i18n.magic.php",
  'ReplaceTextAlias' => "$IP/extensions/ReplaceText/ReplaceText.alias.php",
  'UrlShortenerAlias' => "$IP/extensions/UrlShortener/UrlShortener.alias.php",
  'UrlShortenerNoTranslateAlias' => "$IP/extensions/UrlShortener/UrlShortener.notranslate-alias.php",
  'SiteScoutAliases' => "$IP/extensions/SiteScout/SiteScout.alias.php",
  'Spoilers' => "$IP/extensions/Spoilers/Spoilers.i18n.php",
  'TemplateSandboxAlias' => "$IP/extensions/TemplateSandbox/TemplateSandbox.alias.php",
  'TocTree' => "$IP/extensions/TocTree/TocTree.i18n.php",
  'VoteNYAlias' => "$IP/extensions/VoteNY/VoteNY.alias.php",
  'VoteNYMagic' => "$IP/extensions/VoteNY/VoteNY.i18n.magic.php",
  'WhoIsWatchingAlias' => "$IP/extensions/WhoIsWatching/src/i18n/Alias.php",
  'HieroglyphsAlias' => "$IP/extensions/wikihiero/wikihiero.alias.php",
  'NativeSvgHandler' => "$IP/extensions/NativeSvgHandler/NativeSvgHandler.i18n.php",
  'ScribuntoMagic' => "$IP/extensions/Scribunto/Scribunto.magic.php",
  'ScribuntoNamespaces' => "$IP/extensions/Scribunto/Scribunto.namespaces.php",
  'AdminLinksAlias' => "$IP/extensions/AdminLinks/AdminLinks.alias.php",
  'ArticleToCategory2' => "$IP/extensions/ArticleToCategory2/ArticleToCategory2.i18n.php",
  'AuthorProtect' => "$IP/extensions/AuthorProtect/AuthorProtect.i18n.php",
  'SocialProfileAlias' => "$IP/extensions/SocialProfile/SocialProfile.alias.php",
  'SocialProfileNamespaces' => "$IP/extensions/SocialProfile/SocialProfile.namespaces.php",
  'AvatarMagic' => "$IP/extensions/SocialProfile/UserProfile/Avatar.magic.i18n.php",
  'UserGiftsAlias' => "$IP/extensions/SocialProfile/UserGifts/UserGifts.alias.php",
  'SystemGiftsAlias' => "$IP/extensions/SocialProfile/SystemGifts/SystemGifts.alias.php",
  'UserActivityAlias' => "$IP/extensions/SocialProfile/UserActivity/UserActivity.alias.php",
  'CreatePage' => "$IP/extensions/CreatePage/CreatePage.i18n.php",
  'CreatePageAlias' => "$IP/extensions/CreatePage/CreatePage.alias.php",
  'CreatePageMagic' => "$IP/extensions/CreatePage/CreatePage.magic.php",
  'CreateRedirect' => "$IP/extensions/CreateRedirect/CreateRedirect.i18n.php",
  'CreateRedirectAlias' => "$IP/extensions/CreateRedirect/CreateRedirect.alias.php",
  'CrossReference' => "$IP/extensions/CrossReference/CrossReference.i18n.php",
  'CSS' => "$IP/extensions/CSS/CSS.i18n.php",
  'CSSMagic' => "$IP/extensions/CSS/CSS.i18n.magic.php",
  'Duplicator' => "$IP/extensions/Duplicator/Duplicator.i18n.php",
  'DuplicatorAlias' => "$IP/extensions/Duplicator/Duplicator.alias.php",
  'FlaggedRevs' => "$IP/extensions/FlaggedRevs/frontend/language/FlaggedRevs.i18n.php",
  'FlaggedRevsMagic' => "$IP/extensions/FlaggedRevs/frontend/language/FlaggedRevs.i18n.magic.php",
  'FlaggedRevsAliases' => "$IP/extensions/FlaggedRevs/frontend/language/FlaggedRevs.alias.php",
  'RevisionReview' => "$IP/extensions/FlaggedRevs/frontend/language/RevisionReview.i18n.php",
  'Stabilization' => "$IP/extensions/FlaggedRevs/frontend/language/Stabilization.i18n.php",
  'ReviewedVersions' => "$IP/extensions/FlaggedRevs/frontend/language/ReviewedVersions.i18n.php",
  'UnreviewedPages' => "$IP/extensions/FlaggedRevs/frontend/language/UnreviewedPages.i18n.php",
  'PendingChanges' => "$IP/extensions/FlaggedRevs/frontend/language/PendingChanges.i18n.php",
  'ProblemChanges' => "$IP/extensions/FlaggedRevs/frontend/language/ProblemChanges.i18n.php",
  'ReviewedPages' => "$IP/extensions/FlaggedRevs/frontend/language/ReviewedPages.i18n.php",
  'StablePages' => "$IP/extensions/FlaggedRevs/frontend/language/StablePages.i18n.php",
  'ConfiguredPages' => "$IP/extensions/FlaggedRevs/frontend/language/ConfiguredPages.i18n.php",
  'QualityOversight' => "$IP/extensions/FlaggedRevs/frontend/language/QualityOversight.i18n.php",
  'ValidationStatistics' => "$IP/extensions/FlaggedRevs/frontend/language/ValidationStatistics.i18n.php",
  'GroupsSidebar' => "$IP/extensions/GroupsSidebar/GroupsSidebar.i18n.php",
  'JavascriptSlideshow' => "$IP/extensions/JavascriptSlideshow/JavascriptSlideshow.i18n.php",
  'JavascriptSlideshowMagic' => "$IP/extensions/JavascriptSlideshow/JavascriptSlideshow.i18n.magic.php",
  'Variables' => "$IP/extensions/Variables/Variables.i18n.php",
  'VariablesMagic' => "$IP/extensions/Variables/Variables.i18n.magic.php",
  'LoopsMagic' => "$IP/extensions/Loops/Loops.i18n.magic.php",
  'MapsMagic' => "$IP/extensions/Maps/Maps.i18n.magic.php",
  'MapsAlias' => "$IP/extensions/Maps/Maps.i18n.alias.php",
  'MassEditRegex' => "$IP/extensions/MassEditRegex/MassEditRegex.i18n.php",
  'MassEditRegexAlias' => "$IP/extensions/MassEditRegex/MassEditRegex.alias.php",
  'MsLinks' => "$IP/extensions/MsLinks/MsLinks.i18n.php",
  'MsCatSelect' => "$IP/extensions/MsCatSelect/MsCatSelect.i18n.php",
  'NewsExtension' => "$IP/extensions/News/News.i18n.php",
  'NoTitle' => "$IP/extensions/NoTitle/NoTitle.i18n.php",
  'NoTitleMagic' => "$IP/extensions/NoTitle/NoTitle.i18n.magic.php",
  'PageNotice' => "$IP/extensions/PageNotice/PageNotice.i18n.php",
  'PollAlias' => "$IP/extensions/Poll/Poll.alias.php",
  'SimpleChanges' => "$IP/extensions/SimpleChanges/SimpleChanges.i18n.php",
  'SimpleChangesAlias' => "$IP/extensions/SimpleChanges/SimpleChanges.alias.php",
  'SimpleTooltip' => "$IP/extensions/SimpleTooltip/SimpleTooltip.i18n.php",
  'SimpleTooltipMagic' => "$IP/extensions/SimpleTooltip/SimpleTooltip.i18n.magic.php",
  'SubpageFun' => "$IP/extensions/SubpageFun/SubpageFun.i18n.php",
  'SubpageFunMagic' => "$IP/extensions/SubpageFun/SubpageFun.i18n.magic.php",
  'Tabs' => "$IP/extensions/Tabs/Tabs.i18n.php",
  'TabsMagic' => "$IP/extensions/Tabs/Tabs.i18n.magic.php",
  'TranslateAlias' => "$IP/extensions/Translate/Translate.alias.php",
  'TranslateMagic' => "$IP/extensions/Translate/Translate.i18n.magic.php",
  'TimedMediaHandlerMagic' => "$IP/extensions/TimedMediaHandler/TimedMediaHandler.i18n.magic.php",
  'TimedMediaHandlerAliases' => "$IP/extensions/TimedMediaHandler/TimedMediaHandler.i18n.alias.php",
  'WebChatAlias' => "$IP/extensions/WebChat/WebChat.alias.php",
  'Widgets' => "$IP/extensions/Widgets/Widgets.i18n.php",
  'WidgetsNamespaces' => "$IP/extensions/Widgets/Widgets.i18n.namespaces.php",
  'WidgetsMagic' => "$IP/extensions/Widgets/Widgets.i18n.magic.php",
  'YouTube' => "$IP/extensions/YouTube/YouTube.i18n.php",
);

$wgMessagesDirs = array (
  'CologneBlue' =>
  array (
    0 => "$IP/skins/CologneBlue/i18n",
  ),
  'Modern' =>
  array (
    0 => "$IP/skins/Modern/i18n",
  ),
  'MonoBook' =>
  array (
    0 => "$IP/skins/MonoBook/i18n",
  ),
  'Vector' =>
  array (
    0 => "$IP/skins/Vector/i18n",
  ),
  'AbuseFilter' =>
  array (
    0 => "$IP/extensions/AbuseFilter/i18n",
  ),
  'AntiSpoof' =>
  array (
    0 => "$IP/extensions/AntiSpoof/i18n",
  ),
  'Babel' =>
  array (
    0 => "$IP/extensions/Babel/i18n",
  ),
  'BetaFeatures' =>
  array (
    0 => "$IP/extensions/BetaFeatures/i18n",
  ),
  'SpecialCentralAuth' =>
  array (
    0 => "$IP/extensions/CentralAuth/i18n",
  ),
  'CheckUser' =>
  array (
    0 => "$IP/extensions/CheckUser/i18n",
  ),
  'cite' =>
  array (
    0 => "$IP/extensions/Cite/i18n",
  ),
  've-cite' =>
  array (
    0 => "$IP/extensions/Cite/modules/ve-cite/i18n",
  ),
  'CiteThisPage' =>
  array (
    0 => "$IP/extensions/CiteThisPage/i18n",
  ),
  'CodeEditor' =>
  array (
    0 => "$IP/extensions/CodeEditor/i18n",
  ),
  'ConfirmEdit' =>
  array (
    0 => "$IP/extensions/ConfirmEdit/i18n",
  ),
  'ReCaptchaNoCaptcha' =>
  array (
    0 => "$IP/extensions/ConfirmEdit/ReCaptchaNoCaptcha/i18n",
  ),
  'Disambiguator' =>
  array (
    0 => "$IP/extensions/Disambiguator/i18n",
  ),
  'Echo' =>
  array (
    0 => "$IP/extensions/Echo/i18n",
    1 => "$IP/extensions/Echo/i18n/api",
  ),
  'Gadgets' =>
  array (
    0 => "$IP/extensions/Gadgets/i18n",
  ),
  'GlobalBlocking' =>
  array (
    0 => "$IP/extensions/GlobalBlocking/i18n",
  ),
  'GlobalCssJs' =>
  array (
    0 => "$IP/extensions/GlobalCssJs/i18n/core",
  ),
  'InputBox' =>
  array (
    0 => "$IP/extensions/InputBox/i18n",
  ),
  'Interwiki' =>
  array (
    0 => "$IP/extensions/Interwiki/i18n",
  ),
  'LocalisationUpdate' =>
  array (
    0 => "$IP/extensions/LocalisationUpdate/i18n",
  ),
  'ManageWiki' =>
  array (
    0 => "$IP/extensions/ManageWiki/i18n",
    1 => "$IP/extensions/CustomHeader/i18n",
  ),
  'MassMessage' =>
  array (
    0 => "$IP/extensions/MassMessage/i18n",
  ),
  'Math' =>
  array (
    0 => "$IP/extensions/Math/i18n",
  ),
  'MirahezeMagic' =>
  array (
    0 => "$IP/extensions/MirahezeMagic/i18n/miraheze",
  ),
  'MirahezeOverrideMessagesMagic' =>
  array (
    0 => "$IP/extensions/MirahezeMagic/i18n/overrides",
  ),
  'Nuke' =>
  array (
    0 => "$IP/extensions/Nuke/i18n",
  ),
  'OATHAuth' =>
  array (
    0 => "$IP/extensions/OATHAuth/i18n",
  ),
  'MWOAuth' =>
  array (
    0 => "$IP/extensions/OAuth/i18n",
  ),
  'ParserFunctions' =>
  array (
    0 => "$IP/extensions/ParserFunctions/i18n",
  ),
  'Poem' =>
  array (
    0 => "$IP/extensions/Poem/i18n",
  ),
  'Renameuser' =>
  array (
    0 => "$IP/extensions/Renameuser/i18n",
  ),
  'SiteMatrix' =>
  array (
    0 => "$IP/extensions/SiteMatrix/i18n",
  ),
  'Timeline' =>
  array (
    0 => "$IP/extensions/Timeline/i18n",
  ),
  'Thanks' =>
  array (
    0 => "$IP/extensions/Thanks/i18n",
  ),
  'TitleBlacklist' =>
  array (
    0 => "$IP/extensions/TitleBlacklist/i18n",
  ),
  'TorBlock' =>
  array (
    0 => "$IP/extensions/TorBlock/i18n",
  ),
  'WikiEditor' =>
  array (
    0 => "$IP/extensions/WikiEditor/i18n",
  ),
  'CLDR' =>
  array (
    0 => "$IP/extensions/cldr/i18n",
  ),
  'AJAXPoll' =>
  array (
    0 => "$IP/extensions/AJAXPoll/i18n",
  ),
  'apex' =>
  array (
    0 => "$IP/skins/apex/i18n",
  ),
  'ArticleFeedbackv5' =>
  array (
    0 => "$IP/extensions/ArticleFeedbackv5/i18n",
  ),
  'ArticleRatings' =>
  array (
    0 => "$IP/extensions/ArticleRatings/i18n",
  ),
  'AutoCreateCategoryPages' =>
  array (
    0 => "$IP/extensions/AutoCreateCategoryPages/i18n",
  ),
  'AutomaticBoardWelcome' =>
  array (
    0 => "$IP/extensions/AutomaticBoardWelcome/i18n",
  ),
  'BlogPage' =>
  array (
    0 => "$IP/extensions/BlogPage/i18n",
  ),
  'MsCalendar' =>
  array (
    0 => "$IP/extensions/MsCalendar/i18n",
  ),
  'CategoryTree' =>
  array (
    0 => "$IP/extensions/CategoryTree/i18n",
  ),
  'CentralNotice' =>
  array (
    0 => "$IP/extensions/CentralNotice/i18n",
  ),
  'CharInsert' =>
  array (
    0 => "$IP/extensions/CharInsert/i18n",
  ),
  'CollapsibleVector' =>
  array (
    0 => "$IP/extensions/CollapsibleVector/i18n",
  ),
  'Comments' =>
  array (
    0 => "$IP/extensions/Comments/i18n",
  ),
  'ContactPage' =>
  array (
    0 => "$IP/extensions/ContactPage/i18n",
  ),
  'CookieWarning' =>
  array (
    0 => "$IP/extensions/CookieWarning/i18n",
  ),
  'CreateWiki' =>
  array (
    0 => "$IP/extensions/CreateWiki/i18n",
  ),
  'DarkVector' =>
  array (
    0 => "$IP/skins/DarkVector/i18n",
  ),
  'DismissableSiteNotice' =>
  array (
    0 => "$IP/extensions/DismissableSiteNotice/i18n",
  ),
  'SkinDuskToDawn' =>
  array (
    0 => "$IP/skins/DuskToDawn/i18n",
  ),
  'DPLforum' =>
  array (
    0 => "$IP/extensions/DPLForum/i18n",
  ),
  'DynamicPageList' =>
  array (
    0 => "$IP/extensions/DynamicPageList/i18n",
    1 => "$IP/extensions/DynamicPageList3/i18n",
  ),
  'Editcount' =>
  array (
    0 => "$IP/extensions/Editcount/i18n",
  ),
  'EditSubpages' =>
  array (
    0 => "$IP/extensions/EditSubpages/i18n",
  ),
  'EducationProgram' =>
  array (
    0 => "$IP/extensions/EducationProgram/i18n",
  ),
  'Erudite' =>
  array (
    0 => "$IP/skins/erudite/i18n",
  ),
  'EventLogging' =>
  array (
    0 => "$IP/extensions/EventLogging/i18n/core",
  ),
  'JsonSchema' =>
  array (
    0 => "$IP/extensions/EventLogging/i18n/jsonschema",
  ),
  'Flow' =>
  array (
    0 => "$IP/extensions/Flow/i18n",
    1 => "$IP/extensions/Flow/i18n/api",
  ),
  'SkinForeground' =>
  array (
    0 => "$IP/skins/foreground/i18n",
  ),
  'SkinGamepress' =>
  array (
    0 => "$IP/skins/Gamepress/i18n",
  ),
  'Graph' =>
  array (
    0 => "$IP/extensions/Graph/i18n",
  ),
  'GuidedTour' =>
  array (
    0 => "$IP/extensions/GuidedTour/i18n",
  ),
  'HeaderTabs' =>
  array (
    0 => "$IP/extensions/HeaderTabs/i18n",
  ),
  'HideSection' =>
  array (
    0 => "$IP/extensions/HideSection/i18n",
  ),
  'ImageMap' =>
  array (
    0 => "$IP/extensions/ImageMap/i18n",
  ),
  'Josa' =>
  array (
    0 => "$IP/extensions/Josa/i18n",
  ),
  'LabeledSectionTransclusion' =>
  array (
    0 => "$IP/extensions/LabeledSectionTransclusion/i18n",
  ),
  'LinkSuggest' =>
  array (
    0 => "$IP/extensions/LinkSuggest/i18n",
  ),
  'MediaWikiChat' =>
  array (
    0 => "$IP/extensions/MediaWikiChat/i18n",
  ),
  'Metrolook' =>
  array (
    0 => "$IP/skins/Metrolook/i18n",
  ),
  'MobileFrontend' =>
  array (
    0 => "$IP/extensions/MobileFrontend/i18n",
  ),
  'Moderation' =>
  array (
    0 => "$IP/extensions/Moderation/i18n",
    1 => "$IP/extensions/Moderation/api/i18n",
  ),
  'ModernSkylight' =>
  array (
    0 => "$IP/skins/ModernSkylight/i18n",
  ),
  'MsUpload' =>
  array (
    0 => "$IP/extensions/MsUpload/i18n",
  ),
  'MultimediaViewer' =>
  array (
    0 => "$IP/extensions/MultimediaViewer/i18n",
  ),
  'MultiBoilerplate' =>
  array (
    0 => "$IP/extensions/MultiBoilerplate/i18n",
  ),
  'NewestPages' =>
  array (
    0 => "$IP/extensions/NewestPages/i18n",
  ),
  'NewSignupPage' =>
  array (
    0 => "$IP/extensions/NewSignupPage/i18n",
  ),
  'Newsletter' =>
  array (
    0 => "$IP/extensions/Newsletter/i18n",
  ),
  'NewUserMessage' =>
  array (
    0 => "$IP/extensions/NewUserMessage/i18n",
  ),
  'NewUsersList' =>
  array (
    0 => "$IP/extensions/NewUsersList/i18n",
  ),
  'Nostalgia' =>
  array (
    0 => "$IP/skins/Nostalgia/i18n",
  ),
  'PagedTiffHandler' =>
  array (
    0 => "$IP/extensions/PagedTiffHandler/i18n",
  ),
  'PageTriage' =>
  array (
    0 => "$IP/extensions/PageTriage/i18n",
  ),
  'PdfBook' =>
  array (
    0 => "$IP/extensions/PdfBook/MediaWiki/PdfBook/i18n",
  ),
  'PDFEmbed' =>
  array (
    0 => "$IP/extensions/PDFEmbed/i18n",
  ),
  'PdfHandler' =>
  array (
    0 => "$IP/extensions/PdfHandler/i18n",
  ),
  'PageImages' =>
  array (
    0 => "$IP/extensions/PageImages/i18n",
  ),
  'Popups' =>
  array (
    0 => "$IP/extensions/Popups/i18n",
  ),
  'TextExtracts' =>
  array (
    0 => "$IP/extensions/TextExtracts/i18n",
  ),
  'ProofreadPage' =>
  array (
    0 => "$IP/extensions/ProofreadPage/i18n",
  ),
  'ProtectSite' =>
  array (
    0 => "$IP/extensions/ProtectSite/i18n",
  ),
  'QuizExtension' =>
  array (
    0 => "$IP/extensions/Quiz/i18n",
  ),
  'SkinRefreshed' =>
  array (
    0 => "$IP/skins/Refreshed/i18n",
  ),
  'RelatedArticles' =>
  array (
    0 => "$IP/extensions/RelatedArticles/i18n",
  ),
  'ReplaceText' =>
  array (
    0 => "$IP/extensions/ReplaceText/i18n",
  ),
  'RSS' =>
  array (
    0 => "$IP/extensions/RSS/i18n",
  ),
  'SandboxLink' =>
  array (
    0 => "$IP/extensions/SandboxLink/i18n",
  ),
  'UrlShortener' =>
  array (
    0 => "$IP/extensions/UrlShortener/i18n",
  ),
  'SiteScout' =>
  array (
    0 => "$IP/extensions/SiteScout/i18n",
  ),
  'Spoilers' =>
  array (
    0 => "$IP/extensions/Spoilers/i18n",
  ),
  'SubPageList3' =>
  array (
    0 => "$IP/extensions/SubPageList3/i18n",
  ),
  'SyntaxHighlight_GeSHi' =>
  array (
    0 => "$IP/extensions/SyntaxHighlight_GeSHi/i18n",
  ),
  'Tabber' =>
  array (
    0 => "$IP/extensions/Tabber//i18n",
  ),
  'TemplateSandbox' =>
  array (
    0 => "$IP/extensions/TemplateSandbox/i18n",
  ),
  'Timeless' =>
  array (
    0 => "$IP/skins/Timeless/i18n",
  ),
  'UniversalLanguageSelector' =>
  array (
    0 => "$IP/extensions/UniversalLanguageSelector/i18n",
  ),
  'Theme' =>
  array (
    0 => "$IP/extensions/Theme/i18n",
  ),
  'MwEmbedSupport' =>
  array (
    0 => "$IP/extensions/MwEmbedSupport/i18n",
  ),
  'MwEmbed.MwEmbedSupport' =>
  array (
    0 => "$IP/extensions/MwEmbedSupport/MwEmbedModules/MwEmbedSupport/i18n",
  ),
  'TitleKey' =>
  array (
    0 => "$IP/extensions/TitleKey/i18n",
  ),
  'TocTree' =>
  array (
    0 => "$IP/extensions/TocTree/i18n",
  ),
  'VisualEditor' =>
  array (
    0 => "$IP/extensions/VisualEditor/lib/ve/i18n",
    1 => "$IP/extensions/VisualEditor/modules/ve-mw/i18n",
    2 => "$IP/extensions/VisualEditor/modules/ve-wmf/i18n",
  ),
  'TemplateData' =>
  array (
    0 => "$IP/extensions/TemplateData/i18n",
  ),
  'VoteNY' =>
  array (
    0 => "$IP/extensions/VoteNY/i18n",
  ),
  'WhoIsWatching' =>
  array (
    0 => "$IP/extensions/WhoIsWatching/i18n",
  ),
  'Wikihiero' =>
  array (
    0 => "$IP/extensions/wikihiero/i18n",
  ),
  'WikiLove' =>
  array (
    0 => "$IP/extensions/WikiLove/i18n",
  ),
  'WikiTextLoggedInOut' =>
  array (
    0 => "$IP/extensions/WikiTextLoggedInOut/i18n",
  ),
  'Scribunto' => "$IP/extensions/Scribunto/i18n",
  'AddHTMLMetaAndTitle' => "$IP/extensions/AddHTMLMetaAndTitle/i18n",
  'AdminLinks' => "$IP/extensions/AdminLinks/i18n",
  'AuthorProtect' => "$IP/extensions/AuthorProtect/i18n",
  'SocialProfile' => "$IP/extensions/SocialProfile/i18n",
  'SocialProfileUserBoard' => "$IP/extensions/SocialProfile/UserBoard/i18n",
  'SocialProfileUserProfile' => "$IP/extensions/SocialProfile/UserProfile/i18n",
  'SocialProfileUserRelationship' => "$IP/extensions/SocialProfile/UserRelationship/i18n",
  'SocialProfileUserStats' => "$IP/extensions/SocialProfile/UserStats/i18n",
  'UserGifts' => "$IP/extensions/SocialProfile/UserGifts/i18n",
  'SystemGifts' => "$IP/extensions/SocialProfile/SystemGifts/i18n",
  'UserActivity' => "$IP/extensions/SocialProfile/UserActivity/i18n",
  'CreatePage' => "$IP/extensions/CreatePage/i18n",
  'CreateRedirect' => "$IP/extensions/CreateRedirect/i18n",
  'CSS' => "$IP/extensions/CSS/i18n",
  'Duplicator' => "$IP/extensions/Duplicator/i18n",
  'FlaggedRevs' => "$IP/extensions/FlaggedRevs/i18n/flaggedrevs",
  'RevisionReview' => "$IP/extensions/FlaggedRevs/i18n/revisionreview",
  'Stabilization' => "$IP/extensions/FlaggedRevs/i18n/stabilization",
  'ReviewedVersions' => "$IP/extensions/FlaggedRevs/i18n/reviewedversions",
  'UnreviewedPages' => "$IP/extensions/FlaggedRevs/i18n/unreviewedpages",
  'PendingChanges' => "$IP/extensions/FlaggedRevs/i18n/pendingchanges",
  'ProblemChanges' => "$IP/extensions/FlaggedRevs/i18n/problemchanges",
  'ReviewedPages' => "$IP/extensions/FlaggedRevs/i18n/reviewedpages",
  'StablePages' => "$IP/extensions/FlaggedRevs/i18n/stablepages",
  'ConfiguredPages' => "$IP/extensions/FlaggedRevs/i18n/configuredpages",
  'QualityOversight' => "$IP/extensions/FlaggedRevs/i18n/qualityoversight",
  'ValidationStatistics' => "$IP/extensions/FlaggedRevs/i18n/validationstatistics",
  'FlaggedRevsApi' => "$IP/extensions/FlaggedRevs/i18n/api",
  'GroupsSidebar' => "$IP/extensions/GroupsSidebar/i18n",
  'Variables' => "$IP/extensions/Variables/i18n",
  'Loops' => "$IP/extensions/Loops/i18n",
  'Validator' => "$IP/extensions/Maps/extensions/Validator/i18n",
  'Maps' => "$IP/extensions/Maps/i18n",
  'MassEditRegex' => "$IP/extensions/MassEditRegex/i18n",
  'Monaco' => "$IP/skins/Monaco/i18n",
  'MsLinks' => "$IP/extensions/MsLinks/i18n",
  'MsCatSelect' => "$IP/extensions/MsCatSelect/i18n",
  'NewsExtension' => "$IP/extensions/News/i18n",
  'NoTitle' => "$IP/extensions/NoTitle/i18n",
  'PageNotice' => "$IP/extensions/PageNotice/i18n",
  'Poll' => "$IP/extensions/Poll/i18n",
  'SimpleChanges' => "$IP/extensions/SimpleChanges/i18n",
  'SimpleTooltip' => "$IP/extensions/SimpleTooltip/i18n",
  'SubpageFun' => "$IP/extensions/SubpageFun/i18n",
  'Tabs' => "$IP/extensions/Tabs/i18n",
  'PageTranslation' => "$IP/extensions/Translate/i18n/pagetranslation",
  'Translate' => "$IP/extensions/Translate/i18n/core",
  'TranslateSearch' => "$IP/extensions/Translate/i18n/search",
  'TranslateSandbox' => "$IP/extensions/Translate/i18n/sandbox",
  'TranslateApi' => "$IP/extensions/Translate/i18n/api",
  'TimedMediaHandler' => "$IP/extensions/TimedMediaHandler/i18n",
  'MwEmbed.EmbedPlayer' => "$IP/extensions/TimedMediaHandler/MwEmbedModules/EmbedPlayer/i18n",
  'MwEmbed.TimedText' => "$IP/extensions/TimedMediaHandler/MwEmbedModules/TimedText/i18n",
  'UserWelcome' => "$IP/extensions/SocialProfile/UserWelcome/i18n",
  'WebChat' => "$IP/extensions/WebChat/i18n",
  'Widgets' => "$IP/extensions/Widgets/i18n",
  'YouTube' => "$IP/extensions/YouTube/i18n",
);
