<?php
/**
 * ManageWiki settings are added using the variable below.
 *
 * name: the displayed name of the setting on Special:ManageWiki.
 * from: a text entry of which extension is required for this setting to work. If added by MediaWiki or a 'global' extension, use 'mediawiki'.
 * type: configuration type. See below for available options.
 * overridedefault: a string/array override default when no existing value exist.
 * help: string providing help information for the setting.
 * section: string name of groupings for settings.
 * requires: an array, string, or integer. See below for available types that can be used here.
 *
 * 'type' can be one of:
 *
 * check: adds a checkbox.
 * databases: adds a drop down selection box for selecting a database.
 * float: adds a textbox with float validation (requires: minfloat and maxfloat which are minimum and maximum float values).
 * integer: adds a textbox with integer validation (requires: minint and maxint which are minimum and maximum integer values).
 * language: adds a dropdown for language selection (all which are known to MediaWiki).
 * list: adds a list of options (requires: options which is an array in form of display => internal value).
 * list-multi: see above, just that multiple can be selected.
 * list-multi-bool: see above, just outputs are $this => $bool.
 * matrix: adds an array of "columns" and "rows". Columns are the top array and rows will be the values.
 * namespace: adds dropdown to select one namespace.
 * namespaces: see above, except multiple namespaces.
 * preferences: adds a drop down selection box for selecting multiple user preferences.
 * skin: adds a drop down selection box for selecting a single enabled skin.
 * skins: adds a drop down selection box for selecting multiple enabled skins.
 * text: adds a single line text entry.
 * timezone: adds a dropdown for timezone selection.
 * url: adds a single line text entry which requires a full URL.
 * user: adds an autocomplete text box to select a single user on the wiki.
 * users: see above, except multiple users.
 * usergroups: adds a drop down selection box for selecting multiple user groups.
 * userrights: adds a drop down selection box for selecting multiple user rights.
 * wikipage: add a textbox which will return an autocomplete drop-down list of wikipages. Returns standardised MediaWiki pages.
 * wikipages: see above, except multiple wikipages.
 *
 * 'requires' can be one of:
 *
 * activeusers: max integer amount of active users a wiki may have in order to be able to modify this setting.
 * articles: max integer amount of articles a wiki may have in order to be able to modify this setting.
 * extensions: array of extensions that must be enabled in order to modify this setting. Different from 'from'. Only use if requires more then one extension.
 * pages: max integer amount of pages a wiki may have in order to be able to modify this setting.
 * permissions: array of permissions a user must have to be able to modify this setting. Regardless of this value, a user must always have the managewiki permission.
 * visibility: can be either 'private' or 'public'. If set to 'private' this setting will only appear on private wikis. If set to 'public' it will only appear on public wikis.
 */

$wgManageWikiSettings = [
	// Anti-Spam
	'wgAbuseFilterActions' => [
		'name' => 'AbuseFilter Actions',
		'from' => 'mediawiki',
		'type' => 'list-multi-bool',
		'allopts' => [
			'block',
			'blockautopromote',
			'degroup',
			'disallow',
			'tag',
			'throttle',
			'warn',
		],
		'options' => [
			'Block' => 'block',
			'BlockAutopromote' => 'blockautopromote',
			'Degroup' => 'degroup',
			'Disallow' => 'disallow',
			'Tag' => 'tag',
			'Throttle' => 'throttle',
			'Warn' => 'warn',
		],
		'overridedefault' => [
			'block' => true,
			'blockautopromote' => true,
			'degroup' => true,
			'disallow' => true,
			'rangeblock' => false,
			'tag' => true,
			'throttle' => true,
			'warn' => true,
		],
		'section' => 'anti-spam',
		'help' => 'The possible actions that can be taken by abuse filters. When adding a new action, check if it is restricted in $wgAbuseFilterRestrictions and, if it is, don\'t forget to add the abusefilter-modify-restricted right to the appropriate user groups.',
		'requires' => [],
	],
	'wgAutoblockExpiry' => [
		'name' => 'Autoblock Expiry',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 315360000,
		'overridedefault' => 86400,
		'section' => 'anti-spam',
		'help' => 'Number of seconds before autoblock entries expire. Minimum value allowed: 0, default: 1 day (86400), maximum: 10 years (315360000).',
		'requires' => [],
	],
	'wgBlockAllowsUTEdit' => [
		'name' => 'Allows blocking users to restrict talk page access',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'Allows the blocking user to grant talk page edit access for the blocked user',
		'requires' => [],
	],
	'wgCookieSetOnAutoblock' => [
		'name' => 'Cookie set on autoblock',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'Determines whether to set a cookie when a user is autoblocked. Doing so means that a blocked user, even after logging out and moving to a new IP address, will still be blocked.',
		'requires' => [],
	],
	'wgCookieSetOnIpBlock' => [
		'name' => 'Cookie set on IP block',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'Determines whether to set a cookie when an IP user is blocked. Doing so means that a blocked user, even after moving to a new IP address, will still be blocked.',
		'requires' => [],
	],
	'wgEmailConfirmToEdit' => [
		'name' => 'Email Confirm To Edit',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'anti-spam',
		'help' => 'Require users to confirm email address before they can edit. This effectively disables IP editing.',
		'requires' => [],
	],
	'wgRestrictionTypes' => [
		'name' => 'Restriction Types',
		'from' => 'mediawiki',
		'type' => 'list-multi',
		'options' => [
			'Edit' => 'edit',
			'Move' => 'move',
			'Create' => 'create',
			'Upload' => 'upload',
			'Delete' => 'delete',
			'Protect' => 'protect',
		],
		'overridedefault' => [
			'edit',
			'move',
			'create',
			'upload',
			'delete',
		],
		'section' => 'anti-spam',
		'help' => 'Actions that can be restricted.',
		'requires' => [],
	],
	'wgProtectSiteLimit' => [
		'name' => 'Protect Site Limit',
		'from' => 'protectsite',
		'type' => 'list',
		'options' => [
			'indefinite' => 'indefinite',
			'10 year' => '10 year',
			'1 week' => '1 week',
		],
		'overridedefault' => '1 week',
		'section' => 'anti-spam',
		'help' => 'Maximum time allowed for protection of the site.',
		'requires' => [],
	],
	'wgProtectSiteDefaultTimeout' => [
		'name' => 'ProtectSite Default Timeout',
		'from' => 'protectsite',
		'type' => 'list',
		'options' => [
			'1 year' => '1 year',
			'6 month' => '6 month',
			'3 month' => '3 month',
			'1 month' => '1 month',
			'1 week' => '1 week',
			'3 day' => '3 day',
			'1 day' => '1 day',
			'1 hour' => '1 hour',
		],
		'overridedefault' => '1 hour',
		'section' => 'anti-spam',
		'help' => 'Default timeout, 1 hour by default.',
		'requires' => [],
	],
	'egApprovedRevsAutomaticApprovals' => [
		'name' => 'Automatically approve new revisions',
		'from' => 'approvedrevs',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'Uncheck this box to require new revisions to be manually approved even if made by an administrator',
		'requires' => [],
	],
	'wgFlaggedRevsProtection' => [
		'name' => 'Flagged Revs Protection',
		'from' => 'flaggedrevs',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'anti-spam',
		'help' => 'This enables Flagged Revs Protection.',
		'requires' => [],
	],
	'wgFlaggedRevsAutoReview' => [
		'name' => 'FlaggedRevs Auto Review',
		'from' => 'flaggedrevs',
		'type' => 'list',
		'options' => [
			'No Auto-Review' => 0,
			'Changes' => 1,
			'Creation' => 2,
			'Changes and Creation' => 3,
		],
		'overridedefault' => 3,
		'section' => 'anti-spam',
		'help' => 'Auto-review settings for edits/new pages.',
		'requires' => [],
	],
	'wgSimpleFlaggedRevsUI' => [
		'name' => 'Simple FlaggedRevs UI',
		'from' => 'flaggedrevs',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'When enabled, this will only distinguish "checked", "quality", and unreviewed.',
		'requires' => [],
	],
	'wgFlaggedRevsLowProfile' => [
		'name' => 'FlaggedRevs Low Profile',
		'from' => 'flaggedrevs',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'For visitors, only show tags/icons for unreviewed/outdated pages when enabled.',
		'requires' => [],
	],

	// Beta Feature related stuff
	'wgEchoUseCrossWikiBetaFeature' => [
		'name' => 'Enable Echo Cross Wiki Beta Feature',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'beta',
		'help' => 'Feature flag for the cross-wiki notifications beta feature.',
		'requires' => [],
	],
	'wgMediaViewerIsInBeta' => [
		'name' => 'Enable Media Viewer Beta Mode',
		'from' => 'multimediaviewer',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'beta',
		'help' => 'This makes Media Viewer a beta feature thus this will not be enabled for all users.',
		'requires' => [],
	],
	'wgPopupsReferencePreviewsBetaFeature' => [
		'name' => 'Popups Reference Previews Beta Feature',
		'from' => 'popups',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'beta',
		'help' => 'Whether Reference Previews should be available as a Beta feature. If false, Reference Previews are enabled for all users by default.',
		'requires' => [],
	],
	'wgVisualEditorEnableDiffPageBetaFeature' => [
		'name' => 'Enable VisualEditor Diff Page Beta Feature',
		'from' => 'visualeditor',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'beta',
		'help' => 'Enable the new visual mode as a beta feature on revision difference pages.',
		'requires' => [],
	],
	'wgVisualEditorEnableWikitextBetaFeature' => [
		'name' => 'Enable VisualEditor Wikitext Beta Feature',
		'from' => 'visualeditor',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'beta',
		'help' => 'Enable the new wikitext mode inside the visual editor as a beta feature. It has many of the tools present in the visual editor, uses a similar design, and allows better switching between the two.',
		'requires' => [],
	],
	'wgVisualEditorShowBetaWelcome' => [
		'name' => 'Enable VisualEditor Show Beta Welcome',
		'from' => 'visualeditor',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'beta',
		'help' => 'Shows a beta welcome for users of VisualEditor.',
		'requires' => [],
	],
	
	// Categories
	'wgCategoryPagingLimit' => [
		'name' => 'Category Paging Limit',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 25,
		'maxint' => 5000,
		'overridedefault' => 200,
		'section' => 'categories',
		'help' => 'Paging limit for items in categories.',
		'requires' => [],
	],
	'wgMSCS_WarnNoCategories' => [
		'name' => 'MsCatSelect warn no categories',
		'from' => 'mscatselect',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'categories',
		'help' => 'By default, if you try to save a page that has no categories assigned, MsCatSelect will ask for confirmation. If you wish to avoid this, unset this option.',
		'requires' => [],
	],
	'wgCategoryTreeDefaultMode' => [
		'name' => 'Category Tree Default Mode',
		'from' => 'categorytree',
		'type' => 'list',
		'overridedefault' => 0,
		'section' => 'categories',
		'options' => [
			'Category' => 0,
			'Pages' => 10,
			'All' => 20,
			'Parents' => 100,
		],
		'help' => 'the default mode to use when no mode attribute is specified in a <categorytree> tag. You also need to set "Category Tree Category Page Mode" if you select the page mode.',
		'requires' => [],
	],
	'wgCategoryTreeCategoryPageMode' => [
		'name' => 'Category Tree Category Page Mode',
		'from' => 'categorytree',
		'type' => 'list',
		'overridedefault' => 0,
		'section' => 'categories',
		'options' => [
			'Category' => 0,
			'Pages' => 10,
			'All' => 20,
			'Parents' => 100,
		],
		'help' => 'The mode to use when rendering trees on category pages.',
		'requires' => [],
	],

	// Discussion
	'wgChatLinkUsernames' => [
		'name' => 'Chat Link to Usernames',
		'from' => 'mediawikichat',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'discussion',
		'help' => 'Link to user pages in the main chat window.',
		'requires' => [],
	],
	'wgChatMeCommand' => [
		'name' => 'Chat Me Command',
		'from' => 'mediawikichat',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'discussion',
		'help' => 'Enable "/me <text>" command that prints a status-type message.',
		'requires' => [],
	],
	'wgCommentStreamsEnableTalk' => [
		'name' => 'CommentStreams Enable Talk',
		'from' => 'commentstreams',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'discussion',
		'help' => 'Enable in talk namespaces',
		'requires' => [],
	],
	'wgCommentStreamsNewestStreamsOnTop' => [
		'name' => 'CommentStreams Newest Streams On Top',
		'from' => 'commentstreams',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'discussion',
		'help' => 'Show newer comments first',
		'requires' => [],
	],
	'wgCommentStreamsUserAvatarPropertyName' => [
		'name' => 'CommentStreams User Avatar Property Name',
		'from' => 'commentstreams',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'discussion',
		'help' => 'If SocialProfile is enabled, it will display an avatar',
		'requires' => [],
	],
	'wgCommentStreamsEnableVoting' => [
		'name' => 'CommentStreams Enable Voting',
		'from' => 'commentstreams',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'discussion',
		'help' => 'Allows logged in users to vote thumbs up, thumbs down, or neither on top level comments.',
		'requires' => [],
	],
	'wgCommentStreamsModeratorFastDelete' => [
		'name' => 'CommentStreams Moderator Fast Delete',
		'from' => 'commentstreams',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'discussion',
		'help' => 'allows users with csdelete right to delete a comment and all of its replies in one action rather than having to individually delete all of the replies first.',
		'requires' => [],
	],
	'wgCommentsSortDescending' => [
		'name' => 'Sort Comments by Descending',
		'from' => 'comments',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'discussion',
		'help' => 'This sorts comments by descending date, with the new comment box and most recent comments at the top when enabled.',
		'requires' => [],
	],
	'wgWebChatServer' => [
		'name' => 'WebChat Server',
		'from' => 'webchat',
		'type' => 'text',
		'overridedefault' => '',
		'section' => 'discussion',
		'help' => 'IRC Server to connect to, not required when using the freenodeChat web client.',
		'requires' => [],
	],
	'wgWebChatChannel' => [
		'name' => 'WebChat Channel',
		'from' => 'webchat',
		'type' => 'text',
		'overridedefault' => '',
		'section' => 'discussion',
		'help' => 'Channel to connect to.',
		'requires' => [],
	],
	'wgWebChatClient' => [
		'name' => 'WebChat Client',
		'from' => 'webchat',
		'type' => 'list',
		'options' => [
			'Freenode' => 'freenodeChat',
			'Other Server' => 'Mibbit',
		],
		'overridedefault' => 'freenodeChat',
		'section' => 'discussion',
		'help' => 'This sets the web client to use. If you are not using Freenode, select Other Server.',
		'requires' => [],
	],
	'wgWikiForumAllowAnonymous' => [
		'name' => 'WikiForum Allow Anonymous',
		'from' => 'wikiforum',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'discussion',
		'help' => 'Allow Anonymous (users who are not logged in) to use WikiForum',
		'requires' => [],
	],
	
	// Edit
	'wmgWikiLicense' => [
		'name' => 'Content License',
		'from' => 'mediawiki',
		'type' => 'list',
		'options' => [
			'All Rights Reserved' => 'arr',
			'Creative Commons BY 4.0' => 'cc-by',
			'Creative Commons BY-NC 4.0' => 'cc-by-nc',
			'Creative Commons BY-ND 4.0' => 'cc-by-nd',
			'Creative Commons BY-SA 4.0' => 'cc-by-sa',
			'Creative Commons BY-SA 2.0 Korea' => 'cc-by-sa-2-0-kr',
			'Creative Commons BY-SA-NC 4.0' => 'cc-by-sa-nc',
			'Creative Commons BY-NC-ND 4.0' => 'cc-by-nc-nd',
			'Public Domain' => 'cc-pd',
			'GNU General Public V3' => 'gpl-v3',
			'No license provided' => 'empty',
		],
		'overridedefault' => 'cc-by-sa',
		'section' => 'edit',
		'help' => 'Each wiki on Miraheze is by default licensed under CC-BY-SA 4.0 although this can be changed to another supported license. If you would like to release the contributions on your wiki under another license, please let us know so that we can make it available to you. Be aware that changing the license on your wiki can have an impact on your community and should not be done lightly.',
		'requires' => [],
	],
	'wgActiveUserDays' => [
		'name' => 'Active User Days',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 400,
		'overridedefault' => 30,
		'section' => 'edit',
		'help' => 'The number of days within which a person must make edits to be considered an "active" user.',
		'requires' => [],
	],
	'wgShowCreditsIfMax' => [
		'name' => 'Editing attribution',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Show more authors.',
		'requires' => [],
	],
	'wgVisualEditorEnableWikitext' => [
		'name' => 'Enable VisualEditor Wikitext mode',
		'from' => 'visualeditor',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'This option allow you to read Wikitext syntax on VisualEditor.',
		'requires' => [],
	],
	'wgVisualEditorUseSingleEditTab' => [
		'name' => 'VisualEditor Use Single Edit Tab',
		'from' => 'visualeditor',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Shows only the "edit" tab. Uses VisualEditor by default if "Make VisualEditor the default editor for all" is set, otherwise defaults to Wikitext.',
		'requires' => [],
	],
	'wgVisualEditorEnableDiffPage' => [
		'name' => 'Enable VisualEditor Diff Page',
		'from' => 'visualeditor',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Enable the new visual mode on revision difference pages by default (not Beta).',
		'requires' => [],
	],
	'wgCodeEditorEnableCore' => [
		'name' => 'CodeEditor Enable Core',
		'from' => 'codeeditor',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'To disable the editor on JavaScript and CSS pages in the MediaWiki, User and other core namespaces, unset this option.',
		'requires' => [],
	],
	'wgScribuntoUseCodeEditor' => [
		'name' => 'Scribunto Use CodeEditor',
		'from' => 'codeeditor',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Set this to use it when editing Module pages.',
		'requires' => [],
	],
	'wgScribuntoUseGeSHi' => [
		'name' => 'Scribunto Use GeSHi (SyntaxHighlight)',
		'from' => 'syntaxhighlight_geshi',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Use SyntaxHighlight_GeSHi extension to highlight syntax.',
		'requires' => [],
	],
	'wgPageCreationLog' => [
		'name' => 'Page Creation Log',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Whether to maintain a log of new page creations, which can be viewed at Special:Log/create.',
		'requires' => [],
	],
	'wgPopupsOptInDefaultState' => [
		'name' => 'Popups Opt In Default State',
		'from' => 'popups',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 1,
		'overridedefault' => 0,
		'section' => 'beta',
		'help' => 'Default Page Previews visibility. Has to be a string as a compatibility with beta feature settings.',
		'requires' => [],
	],

	// Links
	'wgArticleCountMethod' => [
		'name' => 'Article Count Method',
		'from' => 'mediawiki',
		'type' => 'list',
		'options' => [
			'Link' => 'link',
			'Any' => 'any',
		],
		'overridedefault' => 'link',
		'section' => 'links',
		'help' => 'Method used to determine if a page in a content namespace should be counted as a valid content page (article).',
		'requires' => [],
		'script' => [
 			"$IP/maintenance/updateArticleCount.php" => [
				'update' => false,
			],
		],
	],
	'wgCapitalLinks' => [
		'name' => 'Capital Links',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'links',
		'help' => 'Unset this to avoid forcing the first letter of links to capitals.',
		'requires' => [],
		'script' => [
 			"$IP/maintenance/cleanupCaps.php" => [],
		],
	],
	'wgDisplayTitleHideSubtitle' => [
		'name' => 'Don\'t display the page\'s original title below the display title',
		'from' => 'displaytitle',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'links',
		'help' => 'Set this to hide the page\'s original title as a subtitle below the title bar, shown by the Display Title extension.',
		'requires' => [],
	],
	'wgEnableCanonicalServerLink' => [
		'name' => 'Enable Canonical Server Link',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'links',
		'help' => 'Output a <link rel="canonical"> tag on every page indicating the canonical server which should be used, i.e. $wgServer or $wgCanonicalServer.',
		'requires' => [],
	],
	'wgExternalLinkTarget' => [
		'name' => 'External Link Target',
		'from' => 'mediawiki',
		'type' => 'list',
		'options' => [
			'Blank' => '_blank',
			'Default' => false,
		],
		'overridedefault' => false,
		'section' => 'links',
		'help' => 'Set a default target for external links.',
		'requires' => [],
	],
	'wgRottenLinksCurlTimeout' => [
		'name' => 'RottenLinks Timeout Threshold',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 5,
		'maxint' => 120,
		'overridedefault' => 10,
		'section' => 'links',
		'help' => 'Number of seconds before a RottenLinks request returns no response. Min: 5. Max: 120.',
		'requires' => [],
	],

	// Localisation (E.G i18n/timezone etc)
	'wgLocaltimezone' => [
		'name' => 'Timezone',
		'from' => 'mediawiki',
		'type' => 'timezone',
		'overridedefault' => 'UTC',
		'section' => 'localisation',
		'help' => 'This will adapt your wikis time over clock to whatever timezone you choose for all users, however it can be changed through user\'s preferences.',
		'requires' => [],
	],
	'wgTranslateDocumentationLanguageCode' => [
		'name' => 'Translate Documentation Language Code',
		'from' => 'translate',
		'type' => 'list',
		'options' => [
			'info' => 'info',
			'No Documentation' => false,
			'qqq' => 'qqq',
		],
		'overridedefault' => false,
		'section' => 'localisation',
		'help' => 'Language code for message documentation.',
		'requires' => [],
	],
	'wgTranslatePageTranslationULS' => [
		'name' => 'Translate Page Translation ULS',
		'from' => 'translate',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'localisation',
		'help' => 'When user changes interface language via ULS, should we also switch the language of the translatable page?',
		'requires' => [],
	],
	
	'wgMinervaAlwaysShowLanguageButton' => [
		'name' => 'Minerva Always Show Language Button',
		'from' => 'minervaneue',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'localisation',
		'help' => 'Whether to show the language switcher button even if no languages are available for the page.',
		'requires' => [],
	],
	'wgULSAnonCanChangeLanguage' => [
		'name' => 'ULS Anon Can Change Language',
		'from' => 'universallanguageselector',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'localisation',
		'help' => 'Enabling allows anonymous users to control the language they view the wiki in.',
		'requires' => [],
	],
	'wgULSPosition' => [
		'name' => 'ULS Position',
		'from' => 'universallanguageselector',
		'type' => 'list',
		'options' => [
			'interlanguage' => 'interlanguage',
			'personal' => 'personal',
		],
		'overridedefault' => 'personal',
		'section' => 'localisation',
		'help' => 'The location and the form of the language selection trigger.',
		'requires' => [],
	],
	'wgPageLanguageUseDB' => [
		'name' => 'Enable per page language',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'localisation',
		'help' => 'Allows to change the page language for MediaWiki pages.',
		'requires' => [],
	],
	'wmgUseYandexTranslate' => [
		'name' => 'Use Yandex Machine Translation on Special:Translate',
		'from' => 'translate',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'localisation',
		'help' => 'Adds suggestions from Yandex to Special:Translate',
		'requires' => [],
	],

	// Maps (E.G navigation)
	'wgKartographerWikivoyageMode' => [
		'name' => 'Kartographer Wikivoyage Mode',
		'from' => 'kartographer',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'maps',
		'help' => 'Enables Wikivoyage mode.',
		'requires' => [],
	],
	'wgKartographerUseMarkerStyle' => [
		'name' => 'Kartographer Use Marker Style',
		'from' => 'kartographer',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'maps',
		'help' => 'Allows Kartographer to extract CSS style to be used by the link from the GeoJSON.',
		'requires' => [],
	],

	// Parser Functions
	'wgDLPAllowUnlimitedResults' => [
		'name' => 'DLP Allow Unlimited Results',
		'from' => 'dynamicpagelist',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'parserfunctions',
		'help' => 'Allows unlimited results with DynamicPageList (Wikimedia).',
		'requires' => [],
	],
	'wgDLPAllowUnlimitedCategories' => [
		'name' => 'DLP Allow Unlimited Categories',
		'from' => 'dynamicpagelist',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'parserfunctions',
		'help' => 'Allows unlimited categories with DynamicPageList (Wikimedia).',
		'requires' => [],
	],
	'wgEnableScaryTranscluding' => [
		'name' => 'Enable Scary Transcluding',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'parserfunctions',
		'help' => 'Allow templates to be imported/transcluded from another wiki.',
		'requires' => [],
	],
	'wgAllowSlowParserFunctions' => [
		'name' => 'Allow slow parser functions',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'parserfunctions',
		'help' => 'Parser functions are "magic words" that return a value or function, such as time, site details or page names.',
		'requires' => [],
	],
	'wgPFEnableStringFunctions' => [
		'name' => 'Enable string function functionality',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'parserfunctions',
		'help' => 'This option adds support a couple of functions for basic string handling. Example: #pos function returns the position of a given search term within the string. You can learn more in MediaWiki\'s <a href="https://www.mediawiki.org/wiki/Module:String">documentation page</a>',
		'requires' => [],
	],
	'wgAllowDisplayTitle' => [
		'name' => 'Allow Display Title',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'parserfunctions',
		'help' => 'Allows use of {{DISPLAYTITLE}} magic word.',
		'requires' => [],
	],
	'wgRestrictDisplayTitle' => [
		'name' => 'Restrict Display Title',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'parserfunctions',
		'help' => 'Restrict {{DISPLAYTITLE}} to titles that normalize to the same canonical database key. Wikis with NoTitle extension installed have this config unset.',
		'requires' => [],
	],

	// Media/File
	'wgEnableUploads' => [
		'name' => 'Enable File Uploads',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'Check or uncheck this option if you want to enable or disable the upload of files on your wiki.',
		'requires' => [],
	],
	'wgAllowCopyUploads' => [
		'name' => 'Enable File Uploads Through URL',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'By default, Miraheze enables file upload only from a local media but with this option you can upload files remotely from other sites.',
		'requires' => [],
	],
	'wgCopyUploadsFromSpecialUpload' => [
		'name' => 'Enable File Uploads Through URL on Special:Upload',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'This option adds a textbox on Special:Upload enabling you to upload files from any URL.',
		'requires' => [],
	],
	'wgUseInstantCommons' => [
		'name' => 'Enable Wikimedia Commons Files',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'This option allows you to use the WikiMedia Commons file database on your wiki.',
		'requires' => [],
	],
	'wgMirahezeCommons' => [
		'name' => 'Enable Miraheze Commons (linking to commons.miraheze.org)',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'This option allows you to use the Miraheze Commons file database on your wiki.',
		'requires' => [],
	],
	'wgShowArchiveThumbnails' => [
		'name' => 'Show Old Thumbnails On Description Page',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'Whether to show thumbnails for old images on the image\'s description page.',
		'requires' => [],
	],
	'wgAllowExternalImages' => [
		'name' => 'Allow External Images',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'Determines whether or not MediaWiki will allow external images to be rendered inline with text',
		'requires' => [],
	],
	'wgSVGConverter' => [
		'name' => 'SVG Converter',
		'from' => 'mediawiki',
		'type' => 'list',
		'options' => [
			'Inkscape' => 'inkscape',
			'ImageMagick' => 'ImageMagick',
		],
		'overridedefault' => 'ImageMagick',
		'section' => 'media',
		'help' => 'This picks the converter to convert Scalable Vector Graphics (SVG) to PNG. You may want to choose Inkscape if your SVG->PNG conversion results in a black image.',
		'requires' => [],
	],
	'wgMediaViewerEnableByDefault' => [
		'name' => 'MediaViewer Enable By Default',
		'from' => 'multimediaviewer',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'This enables MediaViewer for everyone.',
		'requires' => [],
	],
	'wgMSU_checkAutoCat' => [
		'name' => 'MsUpload check auto cat',
		'from' => 'msupload',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'If set, sets the checkbox for adding a category to a page by default.',
		'requires' => [],
	],
	'wgMSU_confirmReplace' => [
		'name' => 'MsUpload confirm replace',
		'from' => 'msupload',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'If set, shows the "Replace file" checkbox.',
		'requires' => [],
	],
	'wgMSU_showAutoCat' => [
		'name' => 'MsUpload show auto cat',
		'from' => 'msupload',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'If set, files uploaded while editing a category page will be added to that category.',
		'requires' => [],
	],
	'wgMSU_useDragDrop' => [
		'name' => 'MsUpload use drag and drop',
		'from' => 'msupload',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'If set, the drag & drop area will be shown.',
		'requires' => [],
	],
	'wgMaxImageArea' => [
		'name' => 'Max Image Area',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => '1.25e7',
		'section' => 'media',
		'help' => 'Specifies the max pixels you can have in a image.',
		'requires' => [],
	],
	'wgCommonsMetadataForceRecalculate' => [
		'name' => 'Force Remote Image Description Parsing',
		'from' => 'commonsmetadata',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'Set this to true to force CommonsMetadata to parse the description page of the image and extract the metadata when using images from other wikis.',
		'requires' => [],
	],
	'wgFileExtensions' => [
		'name' => 'File Extensions',
		'from' => 'mediawiki',
		'type' => 'list-multi',
		'options' => [
			'add' => 'add',
			'alist' => 'alist',
			'apk' => 'apk',
			'apng' => 'apng',
			'asv' => 'asv',
			'avi' => 'avi',
			'bfwav' => 'bfwav',
			'bib' => 'bib',
			'bmp' => 'bmp',
			'bnk' => 'bnk',
			'bst' => 'bst',
			'bz' => 'bz',
			'bz2' => 'bz2',
			'c' => 'c',
			'cap' => 'cap',
			'chr' => 'chr',
			'cls' => 'cls',
			'cpp' => 'cpp',
			'crt' => 'crt',
			'css' => 'css',
			'dae' => 'dae',
			'dat' => 'dat',
			'data' => 'data',
			'desktop' => 'desktop',
			'dia' => 'dia',
			'djvu' => 'djvu',
			'doc' => 'doc',
			'docx' => 'docx',
			'eot' => 'eot',
			'fig' => 'fig',
			'fla' => 'fla',
			'flac' => 'flac',
			'fpd' => 'fpd',
			'gb' => 'gb',
			'gba' => 'gba',
			'gbc' => 'gbc',
			'gbs' => 'gbs',
			'gif' => 'gif',
			'gp' => 'gp',
			'gps' => 'gps',
			'gpx' => 'gpx',
			'gz' => 'gz',
			'gz2' => 'gz2',
			'h' => 'h',
			'hes' => 'hes',
			'hpp' => 'hpp',
			'hxx' => 'hxx',
			'ico' => 'ico',
			'ini' => 'ini',
			'ipe' => 'ipe',
			'ips' => 'ips',
			'jfif' => 'jfif',
			'jpeg' => 'jpeg',
			'jpg' => 'jpg',
			'lua' => 'lua',
			'm4a' => 'm4a',
			'mat' => 'mat',
			'mbz' => 'mbz',
			'md' => 'md',
			'mid' => 'mid',
			'midi' => 'midi',
			'mkv' => 'mkv',
			'mov' => 'mov',
			'mp3' => 'mp3',
			'mp4' => 'mp4',
			'mus' => 'mus',
			'naf' => 'naf',
			'nes' => 'nes',
			'nsf' => 'nsf',
			'odg' => 'odg',
			'odp' => 'odp',
			'ods' => 'ods',
			'odt' => 'odt',
			'off' => 'off',
			'oga' => 'oga',
			'ogg' => 'ogg',
			'ogv' => 'ogv',
			'ogx' => 'ogx',
			'opus' => 'opus',
			'otf' => 'otf',
			'otg' => 'otg',
			'pcap' => 'pcap',
			'pdf' => 'pdf',
			'perf' => 'perf',
			'plot' => 'plot',
			'png' => 'png',
			'pps' => 'pps',
			'ppt' => 'ppt',
			'pptx' => 'pptx',
			'psd' => 'psd',
			'pub' => 'pub',
			'rar' => 'rar',
			'rtf' => 'rtf',
			'scss' => 'scss',
			'sfnt' => 'sfnt',
			'sh' => 'sh',
			'smc' => 'smc',
			'spc' => 'spc',
			'spl' => 'spl',
			'stl' => 'stl',
			'sty' => 'sty',
			'svg' => 'svg',
			'swf' => 'swf',
			'tar' => 'tar',
			'tar.gz' => 'tar.gz',
			'tex' => 'tex',
			'tif' => 'tif',
			'tiff' => 'tiff',
			'ttf' => 'ttf',
			'txt' => 'txt',
			'val' => 'val',
			'vit' => 'vit',
			'vsd' => 'vsd',
			'vst' => 'vst',
			'wav' => 'wav',
			'webm' => 'webm',
			'webp' => 'webp',
			'wma' => 'wma',
			'wmv' => 'wmv',
			'woff' => 'woff',
			'woff2' => 'woff2',
			'xcf' => 'xcf',
			'xdelta' => 'xdelta',
			'xls' => 'xls',
			'xlsx' => 'xlsx',
			'xlxs' => 'xlxs',
			'xml' => 'xml',
			'xps' => 'xps',
			'zip' => 'zip',
			'7z' => '7z',
		],
		'overridedefault' => [
			'djvu',
			'gif',
			'ico',
			'jpg',
			'jpeg',
			'ogg',
			'pdf',
			'png',
			'svg',
		],
		'section' => 'media',
		'help' => 'This is the list of preferred extensions for uploading files. Uploading files with extensions not selected in this list will trigger a warning.',
		'requires' => [],
	],
	'wgTmhEnableMp4Uploads' => [
		'name' => 'TimedMediaHandler Enable Mp4 Uploads',
		'from' => 'timedmediahandler',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'Allows to upload Mp4 files.',
		'requires' => [],
	],

	// Notifications
	'wmgContactPageRecipientUser' => [
		'name' => 'Contact Page Recipient User',
		'from' => 'contactpage',
		'type' => 'user',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'Set to a valid username with a confirmed email. This user will be the recipient user of the ContactPage extension.',
		'requires' => [],
	],
	'wgUsersNotifiedOnAllChanges' => [
		'name' => 'Users Notified On All Changes',
		'from' => 'mediawiki',
		'type' => 'users',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'Array of usernames who will be sent a notification email for every change which occurs on a wiki.',
		'requires' => [],
	],	
	'wgEchoCrossWikiNotifications' => [
		'name' => 'Echo Cross Wiki Notifications',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Whether to enable the cross-wiki notifications feature.',
		'requires' => [],
	],
	'wgEchoMentionStatusNotifications' => [
		'name' => 'Echo Mention Status Notifications',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Enable mention success/failure notifications.',
		'requires' => [],
	],
	'wmgSiteNoticeOptOut' => [
		'name' => 'Opt out of global Miraheze notices',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'Opts your wiki out of global Miraheze notices, only showing important notices.',
		'requires' => [],
	],
	'wgMinervaEnableSiteNotice' => [
		'name' => 'Minerva Sitenotice',
		'from' => 'minervaneue',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Display the Sitenotice on the Minerva skin.',
		'requires' => [],
	],
	'wgDismissableSiteNoticeForAnons' => [
		'name' => 'Dismissable Site Notice For Anons',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'This allows to set whether or not it should be possible for anonymous visitors of the wiki to dismiss the site notice shown.',
		'requires' => [],
	],
	'wgDiscordAvatarUrl' => [
		'name' => 'Discord Notification Avatar URL',
		'from' => 'mediawiki',
		'type' => 'url',
		'overridedefault' => '',
		'section' => 'notifications',
		'help' => 'Avatar to use for messages. If blank, uses the webhook\'s default avatar.',
		'requires' => [
			'visibility' => 'public',
		],
	],
	'wgDiscordIgnoreMinorEdits' => [
		'name' => 'Discord Notification Ignore Minor Edits',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'Ignore Minor Edits from Discord feeds',
		'requires' => [
			'visibility' => 'public',
		],
	],
	'wgDiscordNotificationBlockedUser' => [
		'name' => 'Discord Notification Blocked User',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Notify on user or IP blocked in MediaWiki.',
		'requires' => [
			'visibility' => 'public',
		],
	],
	'wgDiscordNotificationNewUser' => [
		'name' => 'Discord Notification New User',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Notify on new user added into MediaWiki.',
		'requires' => [
			'visibility' => 'public',
		],
	],
	'wgHAWelcomeStaffGroupName' => [
		'name' => 'HAWelcome Staff Group Name',
		'from' => 'hawelcome',
		'type' => 'text',
		'overridedefault' => 'sysop',
		'section' => 'notifications',
		'help' => 'The name of the group that can serve as a fallback when no sysops have been active in the last 60 days.',
		'requires' => [],
	],
	'wgHAWelcomeSignatureFromPreferences' => [
		'name' => 'HAWelcome Signature From Preferences',
		'from' => 'hawelcome',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'This configuration variable toggles if the signature of the welcomer should be the one they have set in their preferences.',
		'requires' => [],
	],
	
	// Permissions
	'wgImplicitGroups' => [
		'name' => 'Implicit Groups',
		'from' => 'mediawiki',
		'type' => 'usergroups',
		'overridedefault' => [
			'*',
			'user',
			'autoconfirmed'
		],
		'section' => 'permissions',
		'help' => 'Groups that aren\'t shown on Special:Listusers or somewhere else.',
		'requires' => [],
	],
	'wmgWhitelistRead' => [
		'name' => 'Whitelist Read',
		'from' => 'mediawiki',
		'type' => 'wikipages',
		'exists' => false,
		'overridedefault' => false,
		'section' => 'permissions',
		'help' => 'Pages anyone may view.',
		'requires' => [
			'visibility' => 'private',
		],
	],
	
	// Preferences
	'wgHiddenPrefs' => [
		'name' => 'Hidden Preferences',
		'from' => 'mediawiki',
		'type' => 'preferences',
		'overridedefault' => false,
		'section' => 'preferences',
		'help' => 'An array of preferences to hide from Special:Preferences.',
		'requires' => [],
	],
	'wgSkipSkins' => [
		'name' => 'Skip Skins',
		'from' => 'mediawiki',
		'type' => 'skins',
		'whitelistSkipSkins' => true,
		'options' => [],
		'overridedefault' => false,
		'section' => 'preferences',
		'help' => 'Array of skins to remove as a choice from user\'s preferences.',
		'requires' => [],
	],
	'wmgVisualEditorEnableDefault' => [
		'name' => 'Make VisualEditor the default editor for all',
		'from' => 'visualeditor',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'preferences',
		'help' => 'This will make VisualEditor the default editor for all. Sets <code>$wgDefaultUserOptions[\'visualeditor-enable\'] = 1;</code> and <code>$wgDefaultUserOptions[\'visualeditor-editor\'] = \'visualeditor\';</code>',
		'requires' => [],
	],
	'wgPopupsHideOptInOnPreferencesPage' => [
		'name' => 'Popups Hide Opt In On Preferences Page',
		'from' => 'popups',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'preferences',
		'help' => 'Whether the option to enable/disable Page Previews should be hidden on Preferences page. Please note if PopupsBetaFeature is set to true this option will be always hidden.',
		'requires' => [],
	],

	// Recent changes
	'wgFeedLimit' => [
		'name' => 'Feed Limit',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 1,
		'maxint' => 5000,
		'overridedefault' => 50,
		'section' => 'recentchanges',
		'help' => 'Set maximum number of results to return in syndication feeds (RSS, Atom) for eg Recentchanges, Newpages. Min. 1, Max. 5,000',
		'requires' => [],
	],
	'wgRCMaxAge' => [
		'name' => 'RecentChanges max age',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 1,
		'maxint' => 62208000,
		'overridedefault' => 180 * 24 * 3600,
		'section' => 'recentchanges',
		'help' => 'Items in the recentchanges table are periodically purged; entries older than this many seconds will go.',
		'requires' => [],
	],
	'wgRCLinkDays' => [
		'name' => 'RecentChanges Link Days',
		'from' => 'mediawiki',
		'type' => 'list-multi',
		'options' => [
			'1 (86400 seconds)' => 1,
			'3 (259200 seconds)' => 3,
			'7 (604800 seconds)' => 7,
			'14 (1209600 seconds)' => 14,
			'30 (2592000 seconds)' => 30,
			'60 (5184000 seconds)' => 60,
			'90 (7776000 seconds)' => 90,
			'180 (15552000 seconds)' => 180,
			'360 (31104000 seconds)' => 360,
		],
		'overridedefault' => [ 1, 3, 7, 14, 30 ],
		'section' => 'recentchanges',
		'help' => 'List days options to list in the Special:Recentchanges and Special:Recentchangeslinked pages.',
		'requires' => [],
	],
	'wgRCLinkLimits' => [
		'name' => 'RecentChanges Link Limits',
		'from' => 'mediawiki',
		'type' => 'list-multi',
		'options' => [
			'50' => 50,
			'100' => 100,
			'250' => 250,
			'500' => 500,
			'1000' => 1000,
			'1500' => 1500,
			'3000' => 3000,
			'5000' => 5000,
			'10000' => 10000,
		],
		'overridedefault' => [ 50, 100, 250, 500 ],
		'section' => 'recentchanges',
		'help' => 'List changes limits options to list in the Special:Recentchanges and Special:Recentchangeslinked pages.',
		'requires' => [],
	],
	'wgCommentsInRecentChanges' => [
		'name' => 'Enable Comments In RecentChanges',
		'from' => 'comments',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'recentchanges',
		'help' => 'Shows comments in the RecentChanges special page.',
		'requires' => [],
	],
	'wgWikiForumLogsInRC' => [
		'name' => 'Display WikiForum logs in RecentChanges',
		'from' => 'wikiforum',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'recentchanges',
		'help' => 'Toggles the display of WikiForum logs in Special:RecentChanges',
		'requires' => [],
	],
	'wgRCWatchCategoryMembership' => [
		'name' => 'Treat Category Membership as a RecentChange',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'recentchanges',
		'help' => 'Shows changes to category membership as an action in Special:RecentChanges',
		'requires' => [],
	],
	'wgSimpleChangesOnlyContentNamespaces' => [
		'name' => 'Display only content namespaces for Simple Changes',
		'from' => 'simplechanges',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'recentchanges',
		'help' => 'Restricts the list to display only content namespaces',
		'requires' => [],
	],
	'wgSimpleChangesOnlyLatest' => [
		'name' => 'Prevent duplicate titles appearing for Simple Changes',
		'from' => 'simplechanges',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'recentchanges',
		'help' => 'Avoids duplicate titles showing up in the list by only showing changes that match each page&apos;s most recent revision',
		'requires' => [],
	],
	'wgSimpleChangesShowUser' => [
		'name' => 'Display the user name of the user who made the change for Simple Changes',
		'from' => 'simplechanges',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'recentchanges',
		'help' => 'Shows the user name of the user who made the change',
		'requires' => [],
	],

	// Restricted (settings that require the managewiki-restricted right)
	'wgSVGMetadataCutoff' => [
		'name' => 'SVG Metadata Cutoff',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 90000000,
		'overridedefault' => 262144,
		'section' => 'restricted',
		'help' => 'Don\'t read SVG metadata beyond this point.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	// If necessary we can increase maxint.
	'wgMaxArticleSize' => [
		'name' => 'Max Article Size',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 10000,
		'overridedefault' => 2048,
		'section' => 'restricted',
		'help' => 'Maximum page size in kilobytes.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wgMaxCredits' => [
		'name' => 'Editing attribution',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => -1,
		'maxint' => 25,
		'overridedefault' => 0,
		'section' => 'restricted',
		'help' => 'Number of editors to attribute.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wgDisqusShortname' => [
		'name' => 'Disqus Shortname',
		'from' => 'disqustag',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'restricted',
		'help' => 'The Disqus shortname for your site. This is the identifier (or the hostname) you specify when entering your unique Disqus URL. This is required when using the DisqusTag extension.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wgPageDisqusShortname' => [
		'name' => 'PageDisqus Shortname',
		'from' => 'pagedisqus',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'restricted',
		'help' => 'The Disqus shortname for your site. This is the identifier (or the hostname) you specify when entering your unique Disqus URL. This is required when using the PageDisqus extension.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wgHAWelcomeWelcomeUsername' => [
		'name' => 'HAWelcome Welcome Username',
		'from' => 'hawelcome',
		'type' => 'text',
		'overridedefault' => $wgSitename,
		'section' => 'restricted',
		'help' => 'This configuration variable contains the name of the user that should leave the welcome message. If this user is flagged as a bot, the edits will be marked as a bot edit.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wgCompressRevisions' => [
		'name' => 'Compress Revisions',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'restricted',
		'help' => "Compress new page revisions if possible. System administrators: after enabling this, don't forget to manually run <code>sudo -u www-data php /srv/mediawiki/w/maintenance/storage/compressOld.php --wiki={$wi->dbname} --type=gzip</code>.",
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wmgSharedUploadBaseUrl' => [
		'name' => 'Shared Upload Base Url',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'restricted',
		'help' => 'The domain name for the wiki to use as the file repository. Leave empty unless it is a custom domain. By default will be the miraheze subdomain of whatever <code>$wmgSharedUploadDBname</code> is set to below. Do not include https:// or any paths.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wmgSharedUploadDBname' => [
		'name' => 'Shared Upload Database Name',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'restricted',
		'help' => 'The database name for the wiki to use as the file repository. DO NOT ever set this to a private wiki. This value must be a valid Miraheze-hosted wiki database.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wgUploadMissingFileUrl' => [
		'name' => 'Upload Missing File Url',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'restricted',
		'help' => 'Point wikilinks to missing files ("red file links") to a custom URL.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wgUploadNavigationUrl' => [
		'name' => 'Upload Navigation Url',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'restricted',
		'help' => 'Point the upload navigation link in the sidebar to a custom URL.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],
	'wgExpensiveParserFunctionLimit' => [
		'name' => 'Expensive Parser Function Limit',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 50,
		'maxint' => 500,
		'overridedefault' => 99,
		'section' => 'restricted',
		'help' => 'Number of expensive parser functions allowed on a single page. Min: 50. Max: 500.',
		'requires' => [
			'permissions' => [
				'managewiki-restricted',
			],
		],
	],

	// SEO
	'wgDefaultRobotPolicy' => [
		'name' => 'Default Robot Policy',
		'from' => 'mediawiki',
		'type' => 'list',
		'options' => [
			'index,follow' => 'index,follow',
			'noindex,nofollow' => 'noindex,nofollow',
			'index,nofollow' => 'index,nofollow',
		],
		'overridedefault' => 'index,follow',
		'section' => 'seo',
		'help' => 'Allows specifying the default robot policy for all pages on the wiki.',
		'requires' => [],
	],
	'wgTwitterCardType' => [
		'name' => 'Twitter Card Type (WikiSEO)',
		'from' => 'wikiseo',
		'type' => 'list',
		'overridedefault' => 'summery_large_image',
		'section' => 'seo',
		'options' => [
			'Summary' => 'summary',
			'Summary large image' => 'summary_large_image',
		],
		'help' => 'Type of twitter card to use.',
		'requires' => [],
	],
	'wgGoogleSiteVerificationKey' => [
		'name' => 'Google Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'seo',
		'help' => 'Site verification key for Google Search Console.',
		'requires' => [],
	],
	'wgBingSiteVerificationKey' => [
		'name' => 'Bing Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'seo',
		'help' => 'Site verification key for Bing Webmaster Center.',
		'requires' => [],
	],
	'wgFacebookAppId' => [
		'name' => 'Facebook App Id (WikiSEO)',
		'from' => 'wikiseo',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'seo',
		'help' => 'App Id for Facebook Insights.',
		'requires' => [],
	],
	'wgYandexSiteVerificationKey' => [
		'name' => 'Yandex Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'seo',
		'help' => 'Site verification key for Yandex Webmasters.',
		'requires' => [],
	],
	'wgAlexaSiteVerificationKey' => [
		'name' => 'Alexa Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'seo',
		'help' => 'Site verification key for Alexa Console.',
		'requires' => [],
	],
	'wgPinterestSiteVerificationKey' => [
		'name' => 'Pinterest Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'seo',
		'help' => 'Site verification key for Pinterest Console.',
		'requires' => [],
	],

	// SocialTools
	'wgCosmosSocialProfileModernTabs' => [
		'name' => 'Cosmos Modern Profile Tabs',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'socialtools',
		'help' => 'Modern profile tabs for the Cosmos skin when social profile is enabled.',
		'requires' => [
			'extensions' => [
				'cosmos',
				'socialprofile',
			],
		],
	],
	'wgCosmosSocialProfileRoundAvatar' => [
		'name' => 'Cosmos Round Avatar',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'socialtools',
		'help' => 'Make avatar round on profile pages for the Cosmos skin when social profile is enabled.',
		'requires' => [
			'extensions' => [
				'cosmos',
				'socialprofile',
			],
		],
	],
	'wgCosmosSocialProfileShowEditCount' => [
		'name' => 'Cosmos Show Edit Count',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'socialtools',
		'help' => 'Show edit count on profile pages for the Cosmos skin when social profile is enabled.',
		'requires' => [
			'extensions' => [
				'cosmos',
				'socialprofile',
			],
		],
	],
	'wgCosmosSocialProfileAllowBio' => [
		'name' => 'Cosmos Allow Bio',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'socialtools',
		'help' => 'Allow users to add a bio from Special:MyPage/bio and display it on their user page?',
		'requires' => [
			'extensions' => [
				'cosmos',
				'socialprofile',
			],
		],
	],
	'wgCosmosSocialProfileFollowBioRedirects' => [
		'name' => 'Cosmos Follow Bio Redirects',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'socialtools',
		'help' => 'Follow redirects from Special:MyPage/bio and display the redirect target as bio instead? (experimental)',
		'requires' => [
			'extensions' => [
				'cosmos',
				'socialprofile',
			],
		],
	],
	'wgCosmosSocialProfileShowGroupTags' => [
		'name' => 'Cosmos Enable Group Tags',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'socialtools',
		'help' => 'Show user group tags on profile pages for the Cosmos skin when social profile is enabled.',
		'requires' => [
			'extensions' => [
				'cosmos',
				'socialprofile',
			],
		],
	],
	'wgCosmosUseSocialProfileAvatar' => [
		'name' => 'Cosmos Use Social Profile Avatar',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'socialtools',
		'help' => 'Use social profile avatar in the top banner for the Cosmos skin when social profile is enabled.',
		'requires' => [
			'extensions' => [
				'cosmos',
				'socialprofile',
			],
		],
	],
	'wgCosmosProfileTagGroups' => [
		'name' => 'Cosmos User Group Tags',
		'from' => 'cosmos',
		'type' => 'usergroups',
		'overridedefault' => [
			'bureaucrat',
			'bot',
			'sysop',
			'interface-admin'
		],
		'section' => 'socialtools',
		'help' => 'User groups to show on profile pages for the Cosmos skin when social profile is enabled. They will be shown in order of priority.',
		'requires' => [
			'extensions' => [
				'cosmos',
				'socialprofile',
			],
		],
	],
	'wgCosmosNumberofGroupTags' => [
		'name' => 'Cosmos Number of Group Tags',
		'from' => 'cosmos',
		'type' => 'integer',
		'minint' => 1,
		'maxint' => 5,
		'overridedefault' => 2,
		'section' => 'socialtools',
		'help' => 'Number of user group tags to show on profile pages for the Cosmos skin when social profile and the profile group tags are enabled. Min. 1; Max. 5.',
		'requires' => [
			'extensions' => [
				'cosmos',
				'socialprofile',
			],
		],
	],
	'wgRandomGameDisplay' => [
		'name' => 'Random Game Display',
		'from' => 'randomgameunit',
		'type' => 'list-multi-bool',
		'allopts' => [
			'random_poll',
			'random_picturegame',
			'random_quiz',
		],
		'options' => [
			'Poll' => 'random_poll',
			'PictureGame' => 'random_picturegame',
			'Quiz' => 'random_quiz',
		],
		'overridedefault' => [
			'random_picturegame' => false,
			'random_poll' => false,
			'random_quiz' => false,
		],
		'section' => 'socialtools',
		'help' => 'Controls what games are enabled.',
		'requires' => [],
	],
	'wgFriendingEnabled' => [
		'name' => 'Friending Enabled',
		'from' => 'socialprofile',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'socialtools',
		'help' => 'Decides whether to enable friending or not.',
		'requires' => [],
	],
	'wgUserBoard' => [
		'name' => 'User Board',
		'from' => 'socialprofile',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'socialtools',
		'help' => 'Displays UserBoard-related things on social profile pages.',
		'requires' => [],
	],
	'wgUserProfileDisplay' => [
		'name' => 'User Profile Display',
		'from' => 'socialprofile',
		'type' => 'list-multi-bool',
		'allopts' => [
			'activity',
			'articles',
			'avatar',
			'awards',
			'board',
			'custom',
			'foes',
			'friends',
			'games',
			'gifts',
			'interests',
			'personal',
			'profile',
			'stats',
			'userboxes',
		],
		'options' => [
			'Activity' => 'activity',
			'Articles' => 'articles',
			'Avatar' => 'avatar',
			'Awards' => 'awards',
			'Board' => 'board',
			'Custom' => 'custom',
			'Foes' => 'foes',
			'Friends' => 'friends',
			'Games' => 'games',
			'Gifts' => 'gifts',
			'Interests' => 'interests',
			'Personal' => 'personal',
			'Profile' => 'profile',
			'Stats' => 'stats',
			'Userboxes' => 'userboxes',
		],
		'overridedefault' => [
			'activity' => false,
			'articles' => true,
			'avatar' => true,
			'awards' => true,
			'board' => false,
			'custom' => true,
			'foes' => false,
			'friends' => false,
			'games' => false,
			'gifts' => true,
			'interests' => true,
			'personal' => true,
			'profile' => true,
			'stats' => false,
			'userboxes' => false,
		],
		'section' => 'socialtools',
		'help' => 'Enables default stuff to display on social profile pages by default',
		'requires' => [],
	],
	
	// Styling (E.G skins/logos etc)
	'wgDefaultSkin' => [
		'name' => 'Default Skin',
		'from' => 'mediawiki',
		'type' => 'skin',
		'options' => [],
		'overridedefault' => 'vector',
		'section' => 'styling',
		'help' => 'Changes the visual interface to the selected skin for all users, however it can be changed through user\'s preferences, unless the skin is added to <code>$wgSkipSkins</code> in the Preferences tab.',
		'requires' => [],
	],
	'wgDefaultMobileSkin' => [
		'name' => 'Default Mobile Skin',
		'from' => 'mobilefrontend',
		'type' => 'skin',
		'options' => [],
		'overridedefault' => 'minerva',
		'section' => 'styling',
		'help' => 'Changes the default mobile skin to be used by the Mobile Frontend extension. Some skins may not be compatable.',
		'requires' => [],
	],
	'wgLogo' => [
		'name' => 'Logo',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => "https://$wmgUploadHostname/metawiki/3/35/Miraheze_Logo.svg",
		'section' => 'styling',
		'help' => 'This will replace Miraheze\'s default logo. See <a href="https://meta.miraheze.org/wiki/ManageWiki#How_do_I_change_my_logo.2Ffavicon.3F">this link</a> for how you can change it. Also sets the value of <code>$wgLogos[\'1x\']</code>.',
		'requires' => [],
	],
	'wgFavicon' => [
		'name' => 'Favicon',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => '/favicon.ico',
		'section' => 'styling',
		'help' => 'A favicon is a shortcut image that is displayed on your visitor\'s browser address bar and in the bookmarks page. Most often it is a smaller version of the logo. See <a href="https://meta.miraheze.org/wiki/ManageWiki#How_do_I_change_my_logo.2Ffavicon.3F">this link</a> for how you can add one.',
		'requires' => [],
	],
	'wgAppleTouchIcon' => [
		'name' => 'Apple Touch Icon',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => '/apple-touch-icon.png',
		'section' => 'styling',
		'help' => 'Favicon for Apple mobile devices. See <a href="https://meta.miraheze.org/wiki/ManageWiki#How_do_I_change_my_logo.2Ffavicon.3F">this link</a> on how you can add one.',
		'requires' => [],
	],
	'wgWordmark' => [
		'name' => 'Wordmark',
		'from' => 'mediawiki',
		'type' => 'url',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'This will set the value of <code>$wgLogos[\'wordmark\'][\'src\']</code>. Also used as wordmark for the Minerva and Cosmos skins.',
		'requires' => [],
	],
	'wgWordmarkWidth' => [
		'name' => 'Wordmark Width',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 9999,
		'overridedefault' => 116,
		'section' => 'styling',
		'help' => 'This will set the width value of the wordmark set by <code>$wgWordmark</code>. For use with the Minerva skin\'s copyright wordmark, this should be set to "116"',
		'requires' => [],
	],
	'wgWordmarkHeight' => [
		'name' => 'Wordmark Height',
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 9999,
		'overridedefault' => 18,
		'section' => 'styling',
		'help' => 'This will set the height value of the wordmark set by <code>$wgWordmark</code>. For use with the Minerva skin\'s copyright wordmark, this should be set to "18"',
		'requires' => [],
	],
	'wmgWikiapiaryFooterPageName' => [
		'name' => 'Wikiapiary Footer Page Name',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => '',
		'section' => 'styling',
		'help' => 'Set to your wiki\'s page name at <a href="https://www.wikiapiary.com">Wikiapiary</a> to add the monitored by Wikiapary footer icon. If you do not have an article there for your wiki, please leave this field blank.',
		'requires' => [],
	],
	'wgCosmosBackgroundImage' => [
		'name' => 'Cosmos Background Image',
		'from' => 'cosmos',
		'type' => 'url',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'Add an image to set as the background image for the wiki\'s body of the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosBackgroundImageSize' => [
		'name' => 'Cosmos Background Image Size',
		'from' => 'cosmos',
		'type' => 'list',
		'options' => [
			'auto' => 'auto',
			'contain' => 'contain',
			'cover' => 'cover',
		],
		'overridedefault' => 'cover',
		'section' => 'styling',
		'help' => 'Add an image to set as the background image for the wiki&apos;s body of the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosWikiHeaderBackgroundImage' => [
		'name' => 'Cosmos Wiki Header Background Image',
		'from' => 'cosmos',
		'type' => 'url',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'Add a background image for the wiki header of the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosMainBackgroundColor' => [
		'name' => 'Cosmos Main Background Color',
		'from' => 'cosmos',
		'type' => 'text',
		'overridedefault' => '#1A1A1A',
		'section' => 'styling',
		'help' => 'Add a color name or hex code to set as the background color for the wiki body of the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosContentBackgroundColor' => [
		'name' => 'Cosmos Content Background Color',
		'from' => 'cosmos',
		'type' => 'text',
		'overridedefault' => '#ffffff',
		'section' => 'styling',
		'help' => 'Add a color name or hex code to set as the background color for the content area of the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosBannerBackgroundColor' => [
		'name' => 'Cosmos Banner Background Color',
		'from' => 'cosmos',
		'type' => 'text',
		'overridedefault' => '#c0c0c0',
		'section' => 'styling',
		'help' => 'Add a color name or hex code to set as the background color for the top banner of the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosWikiHeaderBackgroundColor' => [
		'name' => 'Cosmos Wiki Header Background Color',
		'from' => 'cosmos',
		'type' => 'text',
		'overridedefault' => '#c0c0c0',
		'section' => 'styling',
		'help' => 'Add a color name or hex code to set as the background color of the wiki navigation header on the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosLinkColor' => [
		'name' => 'Cosmos Link Color',
		'from' => 'cosmos',
		'type' => 'text',
		'overridedefault' => '#0645ad',
		'section' => 'styling',
		'help' => 'Add a color name or hex code to set as the link color for the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosButtonBackgroundColor' => [
		'name' => 'Cosmos Button Background Color',
		'from' => 'cosmos',
		'type' => 'text',
		'overridedefault' => '#c0c0c0',
		'section' => 'styling',
		'help' => 'Add a color name or hex code to set as the button background color for the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosToolbarBackgroundColor' => [
		'name' => 'Cosmos Toolbar Background Color',
		'from' => 'cosmos',
		'type' => 'text',
		'overridedefault' => '#000000',
		'section' => 'styling',
		'help' => 'Add a color name or hex code to set as the toolbar background color for the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosFooterBackgroundColor' => [
		'name' => 'Cosmos Footer Background Color',
		'from' => 'cosmos',
		'type' => 'text',
		'overridedefault' => '#c0c0c0',
		'section' => 'styling',
		'help' => 'Add a color name or hex code to set as the footer background color for the Cosmos skin.',
		'requires' => [],
	],
	'wgCosmosBackgroundImageRepeat' => [
		'name' => 'Cosmos Background Image Repeat',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'Repeat the background for the cosmos skin?',
		'requires' => [],
	],
	'wgCosmosBackgroundImageFixed' => [
		'name' => 'Cosmos Background Image Fixed',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'Make the background for the cosmos skin "position: fixed"?',
		'requires' => [],
	],
	'wgCosmosContentOpacityLevel' => [
		'name' => 'Cosmos Content Opacity Level',
		'from' => 'cosmos',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 100,
		'overridedefault' => 100,
		'section' => 'styling',
		'help' => 'Set the opacity level of the content area and custom sidebar for the Cosmos skin in precentage',
		'requires' => [],
	],
	'wgCosmosEnablePortableInfoboxEuropaTheme' => [
		'name' => 'Enable Europa Theme for Infoboxes on Cosmos',
		'from' => 'cosmos',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'Enable the Europa theme on infoboxes when using the Cosmos skin, if you have the PortableInfobox extension enabled.',
		'requires' => [
			'extensions' => [
				'cosmos',
				'portableinfobox',
			],
		],
	],
	'wgLibertyMainColor' => [
		'name' => 'Liberty Main Color',
		'from' => 'liberty',
		'type' => 'text',
		'overridedefault' => '#4188F1',
		'section' => 'styling',
		'help' => 'Theme-color configurations, main color of site.',
		'requires' => [],
	],
	'wgLibertySecondColor' => [
		'name' => 'Liberty Second Color',
		'from' => 'liberty',
		'type' => 'text',
		'overridedefault' => '#2774DC',
		'section' => 'styling',
		'help' => 'Configuration for secondary color of site.',
		'requires' => [],
	],
	'wgMedikColor' => [
		'name' => 'Medik Color',
		'from' => 'medik',
		'type' => 'text',
		'overridedefault' => '#FFBE00',
		'section' => 'styling',
		'help' => 'The Medik color scheme (navbar background, underlines etc.).',
		'requires' => [],
	],
	'wgMedikShowLogo' => [
		'name' => 'Medik Show Logo',
		'from' => 'medik',
		'type' => 'list',
		'options' => [
			'none' => 'none',
			'main' => 'main',
			'sidebar' => 'sidebar'
		],
		'overridedefault' => 'none',
		'section' => 'styling',
		'help' => 'Show logo in the navbar or in the sidebar. By default, the logo is hidden.',
		'requires' => [],
	],
	'wgMedikLogoWidth' => [
		'name' => 'Medik Logo Width',
		'from' => 'medik',
		'type' => 'text',
		'overridedefault' => 'default',
		'section' => 'styling',
		'help' => 'Width of the logo in the main navbar (i.e. you have to set <code>$wgMedikShowLogo</code> to <code>\'main\'</code> first).',
		'requires' => [],
	],
	'wgMedikUseLogoWithoutText' => [
		'name' => 'Medik Use Logo Without Text',
		'from' => 'medik',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'Use only logo and hide the site name in the left upper corner of the wiki.',
		'requires' => [],
	],
	'wgMedikResponsive' => [
		'name' => 'Medik Responsive',
		'from' => 'medik',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'If you need to disable the responsiveness of the skin (i.e. you don\'t want the skin to adjust to the screen size), set this to false.',
		'requires' => [],
	],
	'wgMedikContentWidth' => [
		'name' => 'Medik Content Width',
		'from' => 'medik',
		'type' => 'list',
		'options' => [
			'default' => 'default',
			'full' => 'full'
		],
		'overridedefault' => 'default',
		'section' => 'styling',
		'help' => 'At large screens, the main content container (with articles, texts, etc.) is 9/12 of the screen width and sidebar menu takes 2/12 of the screen width. It means that 1/12 of the screen width on the right side remains white. This is the default and looks good. But there can be cases when you need your wiki to extend to the full width of the screen even on the large screens. Then you can and set this to \'full\'. Then the main content container will take 10/12 of the screen width (and 2/12 remain for the sidebar menu).',
		'requires' => [],
	],
	'wgTimelessBackdropImage' => [
		'name' => 'Timeless Backdrop Image',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => 'cat.svg',
		'section' => 'styling',
		'help' => 'Set to the filename, excluding the File namespace, of a background image to use for the Timeless skin.',
		'requires' => [],
	],
	'wgTimelessLogo' => [
		'name' => 'Timeless Logo',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => null,
		'section' => 'styling',
		'help' => 'Set to the filename, excluding the File namespace, of a logo to use for the Timeless skin.',
		'requires' => [],
	],
	'wgTimelessWordmark' => [
		'name' => 'Timeless Wordmark',
		'from' => 'mediawiki',
		'type' => 'text',
		'overridedefault' => null,
		'section' => 'styling',
		'help' => 'Set to the filename, excluding the File namespace, of a wordmark to use for the Timeless skin.',
		'requires' => [],
	],
	'wgMetrolookDownArrow' => [
		'name' => 'Metrolook Down Arrow',
		'from' => 'metrolook',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'This configuration variable has to be true for the tiles to be generated.',
		'requires' => [],
	],
	'wgMetrolookUploadButton' => [
		'name' => 'Metrolook Upload Button',
		'from' => 'metrolook',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'When enabled, an "Upload file" link is generated in the top menu bar, before the content-specific action links ("History", "Discussion", etc.)',
		'requires' => [],
	],
	'wgMetrolookBartile' => [
		'name' => 'Metrolook Bartile',
		'from' => 'metrolook',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'When "Metrolook Down Arrow" is enabled and "Metrolook Bartile" is enabled, the tile menu will be generated from <a href="/wiki/MediaWiki:Metrolook-tiles">MediaWiki:Metrolook-tiles</a>. If "Metrolook Down Arrow" is not set and "Metrolook Bartile" is not set, then the tile menu will be generated from <a href="/wiki/MediaWiki:Metrolook-tiles-second">MediaWiki:Metrolook-tiles-second</a>.',
		'requires' => [],
	],
	'wgMetrolookMobile' => [
		'name' => 'Metrolook Mobile',
		'from' => 'metrolook',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'When enabled, makes the UI responsive on mobiles.',
		'requires' => [],
	],
	'wgMetrolookUseIconWatch' => [
		'name' => 'Metrolook Use Icon Watch',
		'from' => 'metrolook',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'When enabled, it uses an icon for the watch/unwatch button.',
		'requires' => [],
	],
	'wgMetrolookLine' => [
		'name' => 'Metrolook Line',
		'from' => 'metrolook',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'If not set, then the img.line element (white divider line in the top menu, between the site name and the down arrow/"Upload file" link) won\'t be generated.',
		'requires' => [],
	],
	'wgRelatedArticlesFooterWhitelistedSkins' => [
		'name' => 'RelatedArticles Footer Whitelisted Skins',
		'from' => 'relatedarticles',
		'type' => 'skins',
		'options' => [],
		'overridedefault' => [
			'minerva',
			'timeless',
			'vector'
		],
		'section' => 'styling',
		'help' => 'List of skin names (e.g. "minerva", "vector") where related articles will be shown in the footer.',
		'requires' => [],
	],
	'wgMultiBoilerplateDiplaySpecialPage' => [
		'name' => 'MultiBoilerplate Diplay SpecialPage',
		'from' => 'multiboilerplate',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'if set, will add to the wiki a page named Special:Boilerplates that shows the currently configured boilerplates.',
		'requires' => [],
	],
	'wgAllowUserCss' => [
		'name' => 'Allow User Css',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'Allow user Cascading Style Sheets (CSS). For example User:<user>/*.css.',
		'requires' => [],
	],
	'wgAllowUserJs' => [
		'name' => 'Allow User Js',
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'Allow user JavaScript pages. For example User:<user>/*.js.',
		'requires' => [],
	],
	'wgDefaultTheme' => [
		'name' => 'Default Theme',
		'from' => 'theme',
		'type' => 'list',
		'options' => [
			'Default' => 'default',
			'Dark (Monobook and Vector only)' => 'dark',
			'Deepsea (Vector only)' => 'deepsea',
			'Pink (Monobook only)' => 'pink',
			'Stellarbook (Monobook only)' => 'stellarbook',
		],
		'overridedefault' => 'default',
		'section' => 'styling',
		'help' => 'Sets which theme is displayed by default when users visit your wiki.',
		'requires' => [],
	],
	'wmgShowPopupsByDefault' => [
		'name' => 'Show Popups by default',
		'from' => 'popups',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'When enabled, this shows Popups by default.',
		'requires' => [],
	],

	// Wikibase
	'wmgWikibaseRepoUrl' => [
		'name' => 'Repository URL',
		'from' => 'wikibaseclient',
		'type' => 'url',
		'overridedefault' => 'https://wikidata.org',
		'section' => 'wikibase',
		'help' => 'URL of the Wikibase repository the client should connect to.',
		'requires' => [],
	],
	'wmgWikibaseRepoDatabase' => [
		'name' => 'Repository Database',
		'from' => 'wikibaseclient',
		'type' => 'databases',
		'overridedefault' => $wi->dbname,
		'section' => 'wikibase',
		'help' => 'Database identifier of the repository being used. This value must be a valid Miraheze-hosted wiki database.',
		'requires' => [],
	],
	'wmgAllowEntityImport' => [
		'name' => 'Allow Entity Import',
		'from' => 'wikibaserepository',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'wikibase',
		'help' => 'Allow importing entities via Special:Import and importDump.php.',
		'requires' => [],
	],
	'wmgEnableEntitySearchUI' => [
		'name' => 'Enable Entity Search UI',
		'from' => 'wikibaserepository',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'wikibase',
		'help' => 'To determine if entity search UI should be enabled or not.',
		'requires' => [],
	],
	'wmgFederatedPropertiesEnabled' => [
		'name' => 'Enable Federated Properties',
		'from' => 'wikibaserepository',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'wikibase',
		'help' => 'To determine if federated properties should be enabled or not.',
		'requires' => [],
	],
	'wmgWikibaseItemNamespaceID' => [
		'name' => 'Item Namespace ID',
		'from' => 'wikibaseclient',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 9999,
		'overridedefault' => 0,
		'section' => 'wikibase',
		'help' => 'Namespace ID of the Item namespace on the upstream Wikibase installation. Leave as-is if unsure.',
		'requires' => [],
	],
	'wmgWikibasePropertyNamespaceID' => [
		'name' => 'Property Namespace ID',
		'from' => 'wikibaseclient',
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 9999,
		'overridedefault' => 120,
		'section' => 'wikibase',
		'help' => 'Namespace ID of the Property namespace on the upstream Wikibase installation. Leave as-is if unsure.',
		'requires' => [],
	]
];
