<?php

/**
 * ManageWiki settings are added using the variable below.
 *
 * Type can be either:
 *
 * check: adds a checkbox.
 * databases: adds a drop down selection box for selecting a database.
 * float: adds a textbox with float validation (requires: minfloat and maxfloat which are minimum and maximum float values).
 * integer: adds a textbox with integer validation (requires: minint and maxint which are minimum and maximum integer values).
 * language: adds a dropdown for language selection (all which are known to MediaWiki).
 * list: adds a list of options (requires: options which is an array in form of display => internal value).
 * list-multi: see above, just that multiple can be selected.
 * list-multi-bool: see above, just outputs are $this => $bool.
 * matrix: adds an array of "columns" and "rows". Columns are the top array and rows will be the values.
 * namespace: adds dropdown to select one namespace.
 * namespaces: see above, except multiple namespaces.
 * skin: adds a drop down selection box for selecting a single enabled skin.
 * skins: adds a drop down selection box for selecting multiple enabled skins.
 * text: adds a single line text entry.
 * timezone: adds a dropdown for timezone selection.
 * url: adds a single line text entry which requires a full URL.
 * user: adds an autocomplete text box to select a single user on the wiki.
 * users: see above, except multiple users.
 * usergroups: adds a drop down selection box for selecting multiple user groups.
 * userrights: adds a drop down selection box for selecting multiple user rights.
 * wikipage: add a textbox which will return an autocomplete drop-down list of wikipages. Returns standardised MediaWiki pages.
 * wikipages: see above, except multiple wikipages.
 *
 * Other variables that are required are name and from.
 *
 * name: the displayed name of the setting on Special:ManageWiki.
 * from: a text entry of which extension is required for this setting to work. If added by MediaWiki or a 'global' extension, use 'mediawiki'.
 * overridedefault: a string/array override default when no existing value exist.
 * restricted: boolean - requires managewiki-restricted to change.
 * help: string providing help information for the setting.
 * section: string name of groupings for settings.
 */
$wgManageWikiSettings = [
	// Anti-Spam
	'wgAbuseFilterActions' => [
		'name' => 'AbuseFilter Actions',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'list-multi-bool',
		'allopts' => [
			'block',
			'blockautopromote',
			'degroup',
			'disallow',
			'tag',
			'throttle',
			'warn',
		],
		'options' => [
			'Block' => 'block',
			'BlockAutopromote' => 'blockautopromote',
			'Degroup' => 'degroup',
			'Disallow' => 'disallow',
			'Tag' => 'tag',
			'Throttle' => 'throttle',
			'Warn' => 'warn',
		],
		'overridedefault' => [
			'block' => true,
			'blockautopromote' => true,
			'degroup' => true,
			'disallow' => true,
			'rangeblock' => false,
			'tag' => true,
			'throttle' => true,
			'warn' => true,
		],
		'section' => 'anti-spam',
		'help' => 'The possible actions that can be taken by abuse filters. When adding a new action, check if it is restricted in $wgAbuseFilterRestrictions and, if it is, don\'t forget to add the abusefilter-modify-restricted right to the appropriate user groups.',
	],
	'wgAutoblockExpiry' => [
		'name' => 'Autoblock Expiry',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 315360000,
		'overridedefault' => 86400,
		'section' => 'anti-spam',
		'help' => 'Number of seconds before autoblock entries expire. Minimum value allowed: 0, default: 1 day (86400), maximum: 10 years (315360000).',
	],
	'wgBlockAllowsUTEdit' => [
		'name' => 'Allows blocking users to restrict talk page access',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'Allows the blocking user to grant talk page edit access for the blocked user',
	],
	'wgCookieSetOnAutoblock' => [
		'name' => 'Cookie set on autoblock',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'Determines whether to set a cookie when a user is autoblocked. Doing so means that a blocked user, even after logging out and moving to a new IP address, will still be blocked.',
	],
	'wgCookieSetOnIpBlock' => [
		'name' => 'Cookie set on IP block',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'Determines whether to set a cookie when an IP user is blocked. Doing so means that a blocked user, even after moving to a new IP address, will still be blocked.',
	],
	'wgEmailConfirmToEdit' => [
		'name' => 'Email Confirm To Edit',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'anti-spam',
		'help' => 'Require users to confirm email address before they can edit. This effectively disables IP editing.',
	],
	'wgProtectSiteLimit' => [
		'name' => 'Protect Site Limit',
		'from' => 'protectsite',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'indefinite' => 'indefinite',
			'10 year' => '10 year',
			'1 week' => '1 week',
		],
		'overridedefault' => '1 week',
		'section' => 'anti-spam',
		'help' => 'Maximum time allowed for protection of the site.',
	],
	'wgProtectSiteDefaultTimeout' => [
		'name' => 'ProtectSite Default Timeout',
		'from' => 'protectsite',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'1 year' => '1 year',
			'6 month' => '6 month',
			'3 month' => '3 month',
			'1 month' => '1 month',
			'1 week' => '1 week',
			'3 day' => '3 day',
			'1 day' => '1 day',
			'1 hour' => '1 hour',
		],
		'overridedefault' => '1 hour',
		'section' => 'anti-spam',
		'help' => 'Default timeout, 1 hour by default.',
	],
	'wgFlaggedRevsProtection' => [
		'name' => 'Flagged Revs Protection',
		'from' => 'flaggedrevs',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'anti-spam',
		'help' => 'This enables Flagged Revs Protection.',
	],
	'wgFlaggedRevsAutoReview' => [
		'name' => 'FlaggedRevs Auto Review',
		'from' => 'flaggedrevs',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'No Auto-Review' => 0,
			'Changes' => 1,
			'Creation' => 2,
			'Changes and Creation' => 3,
		],
		'overridedefault' => 3,
		'section' => 'anti-spam',
		'help' => 'Auto-review settings for edits/new pages.',
	],
	'wgFlaggedRevsRestrictionLevels' => [
		'name' => 'FlaggedRevs Restriction Levels',
		'from' => 'flaggedrevs',
		'restricted' => false,
		'type' => 'usergroups',
		'options' => [
			'No Restriction' => '',
		],
		'overridedefault' => [
			'',
			'user',
			'autoconfirmed',
			'sysop'
		],
		'section' => 'anti-spam',
		'help' => 'Restriction levels for "autoreview"/"review" rights.',
	],
	'wgSimpleFlaggedRevsUI' => [
		'name' => 'Simple FlaggedRevs UI',
		'from' => 'flaggedrevs',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'When enabled, this will only distinguish "checked", "quality", and unreviewed.',
	],
	'wgFlaggedRevsLowProfile' => [
		'name' => 'FlaggedRevs Low Profile',
		'from' => 'flaggedrevs',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'anti-spam',
		'help' => 'For visitors, only show tags/icons for unreviewed/outdated pages when enabled.',
	],

	// Beta Feature related stuff
	'wgEchoUseCrossWikiBetaFeature' => [
		'name' => 'Enable Echo Cross Wiki Beta Feature',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'beta',
		'help' => 'Feature flag for the cross-wiki notifications beta feature.',
	],
	'wgMediaViewerIsInBeta' => [
		'name' => 'Enable Media Viewer Beta Mode',
		'from' => 'multimediaviewer',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'beta',
		'help' => 'This makes Media Viewer a beta feature thus this will not be enabled for all users.',
	],
	'wgVisualEditorEnableDiffPageBetaFeature' => [
		'name' => 'Enable VisualEditor Diff Page Beta Feature',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'beta',
		'help' => 'Enable the new visual mode as a beta feature on revision difference pages.',
	],
	'wgVisualEditorEnableWikitextBetaFeature' => [
		'name' => 'Enable VisualEditor Wikitext Beta Feature',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'beta',
		'help' => 'Enable the new wikitext mode inside the visual editor as a beta feature. It has many of the tools present in the visual editor, uses a similar design, and allows better switching between the two.',
	],
	'wgVisualEditorShowBetaWelcome' => [
		'name' => 'Enable VisualEditor Show Beta Welcome',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'beta',
		'help' => 'Shows a beta welcome for users of VisualEditor.',
	],

	// Chat
	'wgChatLinkUsernames' => [
		'name' => 'Chat Link to Usernames',
		'from' => 'mediawikichat',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'chat',
		'help' => 'Link to user pages in the main chat window.',
	],
	'wgChatMeCommand' => [
		'name' => 'Chat Me Command',
		'from' => 'mediawikichat',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'chat',
		'help' => 'Enable "/me <text>" command that prints a status-type message.',
	],
	'wgWebChatServer' => [
		'name' => 'WebChat Server',
		'from' => 'webchat',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '',
		'section' => 'chat',
		'help' => 'IRC Server to connect to, not required when using the freenodeChat web client.',
	],
	'wgWebChatChannel' => [
		'name' => 'WebChat Channel',
		'from' => 'webchat',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '',
		'section' => 'chat',
		'help' => 'Channel to connect to.',
	],
	'wgWebChatClient' => [
		'name' => 'WebChat Client',
		'from' => 'webchat',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'Freenode' => 'freenodeChat',
			'Other Server' => 'Mibbit',
		],
		'overridedefault' => 'freenodeChat',
		'section' => 'chat',
		'help' => 'This sets the web client to use. If you are not using Freenode, select Other Server.',
	],
	
	// Cosmos
	'wgCosmosBannerLogo' => [
		'name' => 'Cosmos Banner Logo',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'url',
		'overridedefault' => null,
		'section' => 'cosmos',
		'help' => 'Add a logo to appear in the top banner on the Cosmos skin.',
	],
	'wgCosmosWikiHeaderWordmark' => [
		'name' => 'Cosmos Wordmark',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'url',
		'overridedefault' => null,
		'section' => 'cosmos',
		'help' => 'Add a wordmark to appear in the wiki header on the Cosmos skin. Not setting this will default the logo to <code>$wgLogo</code>.',
	],
	'wgCosmosBackgroundImage' => [
		'name' => 'Cosmos Background Image',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'url',
		'overridedefault' => null,
		'section' => 'cosmos',
		'help' => 'Add an image to set as the background image for the wiki\'s body of the Cosmos skin.',
	],
	'wgCosmosBackgroundImageSize' => [
		'name' => 'Cosmos Background Image Size',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'auto' => 'auto',
			'contain' => 'contain',
			'cover' => 'cover',
		],
		'overridedefault' => 'cover',
		'section' => 'cosmos',
		'help' => 'Add an image to set as the background image for the wiki&apos;s body of the Cosmos skin.',
	],
	'wgCosmosWikiHeaderBackgroundImage' => [
		'name' => 'Cosmos Wiki Header Background Image',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'url',
		'overridedefault' => null,
		'section' => 'cosmos',
		'help' => 'Add a background image for the wiki header of the Cosmos skin.',
	],
	'wgCosmosMainBackgroundColor' => [
		'name' => 'Cosmos Main Background Color',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '#1A1A1A',
		'section' => 'cosmos',
		'help' => 'Add a color name or hex code to set as the background color for the wiki body of the Cosmos skin.',
	],
	'wgCosmosContentBackgroundColor' => [
		'name' => 'Cosmos Content Background Color',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '#ffffff',
		'section' => 'cosmos',
		'help' => 'Add a color name or hex code to set as the background color for the content area of the Cosmos skin.',
	],
	'wgCosmosBannerBackgroundColor' => [
		'name' => 'Cosmos Banner Background Color',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '#c0c0c0',
		'section' => 'cosmos',
		'help' => 'Add a color name or hex code to set as the background color for the top banner of the Cosmos skin.',
	],
	'wgCosmosWikiHeaderBackgroundColor' => [
		'name' => 'Cosmos Wiki Header Background Color',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '#c0c0c0',
		'section' => 'cosmos',
		'help' => 'Add a color name or hex code to set as the background color of the wiki navigation header on the Cosmos skin.',
	],
	'wgCosmosLinkColor' => [
		'name' => 'Cosmos Link Color',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '#0645ad',
		'section' => 'cosmos',
		'help' => 'Add a color name or hex code to set as the link color for the Cosmos skin.',
	],
	'wgCosmosButtonColor' => [
		'name' => 'Cosmos Button Color',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '#c0c0c0',
		'section' => 'cosmos',
		'help' => 'Add a color name or hex code to set as the button background color for the Cosmos skin.',
	],
	'wgCosmosToolbarColor' => [
		'name' => 'Cosmos Toolbar Color',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '#000000',
		'section' => 'cosmos',
		'help' => 'Add a color name or hex code to set as the toolbar background color for the Cosmos skin.',
	],
	'wgCosmosFooterColor' => [
		'name' => 'Cosmos Footer Color',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '#c0c0c0',
		'section' => 'cosmos',
		'help' => 'Add a color name or hex code to set as the footer background color for the Cosmos skin.',
	],
	'wgCosmosEnablePortableInfoboxEuropaTheme' => [
		'name' => 'Enable Europa Theme for Infoboxes on Cosmos',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'cosmos',
		'help' => 'Enable the Europa theme on infoboxes when using the Cosmos skin, if you have the PortableInfobox extension enabled.',
	],
	'wgCosmosBackgroundImageNorepeat' => [
		'name' => 'Cosmos Background Image Repeat',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'cosmos',
		'help' => 'Repeat the background for the cosmos skin?',
	],
	'wgCosmosBackgroundImageFixed' => [
		'name' => 'Cosmos Background Image Position',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'cosmos',
		'help' => 'Make the background for the cosmos skin "position: fixed"?',
	],
	'wgCosmosUseMessageforToolbar' => [
		'name' => 'Replace Cosmos Toolbar with Message',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'cosmos',
		'help' => 'Replace the existing floating toolbar with the contents of MediaWiki:Cosmos-toolbar? Not checking this will make the contents of MediaWiki:Cosmos-toolbar be appended to the toolbar rather than replacing it.',
	],
	'wgCosmosSocialProfileModernTabs' => [
		'name' => 'Cosmos Modern Profile Tabs',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'cosmos',
		'help' => 'Modern profile tabs for the Cosmos skin when social profile is enabled.',
	],
	'wgCosmosSocialProfileRoundAvatar' => [
		'name' => 'Cosmos Round Avatar',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'cosmos',
		'help' => 'Make avatar round on profile pages for the Cosmos skin when social profile is enabled.',
	],
	'wgCosmosSocialProfileShowEditCount' => [
		'name' => 'Cosmos Show Edit Count',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'cosmos',
		'help' => 'Show edit count on profile pages for the Cosmos skin when social profile is enabled.',
	],
	'wgCosmosSocialProfileAllowBio' => [
		'name' => 'Cosmos Allow Bio Feature',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'cosmos',
		'help' => 'Allow users to add a bio on profile pages for the Cosmos skin when social profile is enabled.',
	],
	'wgCosmosSocialProfileShowGroupTags' => [
		'name' => 'Cosmos Enable Group Tags',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'cosmos',
		'help' => 'Show user group tags on profile pages for the Cosmos skin when social profile is enabled.',
	],
	'wgCosmosUseSocialProfileAvatar' => [
		'name' => 'Cosmos Use Social Profile Avatar',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'cosmos',
		'help' => 'Use social profile avatar in the top banner for the Cosmos skin when social profile is enabled.',
	],
	'wgCosmosProfileTagGroups' => [
		'name' => 'Cosmos User Group Tags',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'usergroups',
		'overridedefault' => [
			'bureaucrat',
			'bot',
			'sysop',
			'interface-admin'
		],
		'section' => 'cosmos',
		'help' => 'User groups to show on profile pages for the Cosmos skin when social profile is enabled. They will be shown in order of priority.',
	],
	'wgCosmosNumberofGroupTags' => [
		'name' => 'Cosmos Number of Group Tags',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'integer',
		'minint' => 1,
		'maxint' => 5,
		'overridedefault' => 2,
		'section' => 'cosmos',
		'help' => 'Number of user group tags to show on profile pages for the Cosmos skin when social profile and the profile group tags are enabled. Min. 1; Max. 5.',
	],
	'wgCosmosContentOpacityLevel' => [
		'name' => 'Cosmos Content Opacity Level',
		'from' => 'cosmos',
		'restricted' => false,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 100,
		'overridedefault' => 100,
		'section' => 'cosmos',
		'help' => 'Set the opacity level of the content area and custom sidebar for the Cosmos skin in precentage',
	],
	
	// Editing
	'wmgWikiLicense' => [
		'name' => 'Content License',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'All Rights Reserved' => 'arr',
			'Creative Commons BY 4.0' => 'cc-by',
			'Creative Commons BY-NC 4.0' => 'cc-by-nc',
			'Creative Commons BY-ND 4.0' => 'cc-by-nd',
			'Creative Commons BY-SA 4.0' => 'cc-by-sa',
			'Creative Commons BY-SA 2.0 Korea' => 'cc-by-sa-2-0-kr',
			'Creative Commons BY-SA-NC 4.0' => 'cc-by-sa-nc',
			'Creative Commons BY-NC-ND 4.0' => 'cc-by-nc-nd',
			'Public Domain' => 'cc-pd',
			'GNU General Public V3' => 'gpl-v3',
			'No license provided' => 'empty',
		],
		'overridedefault' => 'cc-by-sa',
		'section' => 'edit',
		'help' => 'Each wiki on Miraheze is by default licensed under CC-BY-SA 4.0 although this can be changed to another supported license. If you would like to release the contributions on your wiki under another license, please let us know so that we can make it available to you. Be aware that changing the license on your wiki can have an impact on your community and should not be done lightly.',
	],
	'wgActiveUserDays' => [
		'name' => 'Active User Days',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 400,
		'overridedefault' => 30,
		'section' => 'edit',
		'help' => 'The number of days within which a person must make edits to be considered an "active" user.',
	],
	'wgShowCreditsIfMax' => [
		'name' => 'Editing attribution',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Show more authors.',
	],
	'wgRestrictionLevels' => [
		'name' => 'Restriction Levels',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'usergroups',
		'options' => [
			'No Restriction' => '',
		],
		'overridedefault' => [
			'',
			'user',
			'autoconfirmed',
			'sysop'
		],
		'section' => 'edit',
		'help' => 'Set of permission keys that can be selected on the "page protection" page. Must be set to usergroups not userrights.',
	],
	'wgRestrictionTypes' => [
		'name' => 'Restriction Types',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'list-multi',
		'options' => [
			'Edit' => 'edit',
			'Move' => 'move',
			'Create' => 'create',
			'Upload' => 'upload',
			'Delete' => 'delete',
			'Protect' => 'protect',
		],
		'overridedefault' => [
			'edit',
			'move',
			'create',
			'upload',
			'delete',
		],
		'section' => 'edit',
		'help' => 'Actions that can be restricted.',
	],
	'wgImplicitGroups' => [
		'name' => 'Implicit Groups',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'usergroups',
		'overridedefault' => [
			'*',
			'user',
			'autoconfirmed'
		],
		'section' => 'edit',
		'help' => 'Groups that aren\'t shown on Special:Listusers or somewhere else.',
  ],
	'wgCommentStreamsEnableTalk' => [
		'name' => 'CommentStreams Enable Talk',
		'from' => 'commentstreams',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Enable in talk namespaces',
	],
	'wgCommentStreamsNewestStreamsOnTop' => [
		'name' => 'CommentStreams Newest Streams On Top',
		'from' => 'commentstreams',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Show newer comments first',
	],
	'wgCommentStreamsUserAvatarPropertyName' => [
		'name' => 'CommentStreams User Avatar Property Name',
		'from' => 'commentstreams',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'If SocialProfile is enabled, it will display an avatar',
	],
	'wgCommentStreamsEnableVoting' => [
		'name' => 'CommentStreams Enable Voting',
		'from' => 'commentstreams',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Allows logged in users to vote thumbs up, thumbs down, or neither on top level comments.',
	],
	'wgCommentStreamsModeratorFastDelete' => [
		'name' => 'CommentStreams Moderator Fast Delete',
		'from' => 'commentstreams',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'allows users with csdelete right to delete a comment and all of its replies in one action rather than having to individually delete all of the replies first.',
	],
	'wgCommentsSortDescending' => [
		'name' => 'Sort Comments by Descending',
		'from' => 'comments',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'This sorts comments by descending date, with the new comment box and most recent comments at the top when enabled.',
	],
	'wgEnableScaryTranscluding' => [
		'name' => 'Enable Scary Transcluding',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Allow templates to be imported/transcluded from another wiki.',
	],
	'wmgVisualEditorEnableDefault' => [
		'name' => 'Make VisualEditor the default editor for all',
		'from' => 'visualeditor',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'This will make VisualEditor the default edit for all.',
	],
	'wgVisualEditorEnableWikitext' => [
		'name' => 'Enable VisualEditor Wikitext mode',
		'from' => 'visualeditor',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'This option allow you to read Wikitext syntax on VisualEditor.',
	],
	'wgVisualEditorUseSingleEditTab' => [
		'name' => 'VisualEditor Use Single Edit Tab',
		'from' => 'visualeditor',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Shows only the "edit" tab. Uses VisualEditor by default if "Make VisualEditor the default editor for all" is set, otherwise defaults to Wikitext.',
	],
	'wgVisualEditorEnableDiffPage' => [
		'name' => 'Enable VisualEditor Diff Page',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Enable the new visual mode on revision difference pages by default (not Beta).',
	],
	'wgAllowSlowParserFunctions' => [
		'name' => 'Allow slow parser functions',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Parser functions are "magic words" that return a value or function, such as time, site details or page names.',
	],
	'wgPFEnableStringFunctions' => [
		'name' => 'Enable string function functionality',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'This option adds support a couple of functions for basic string handling. Example: #pos function returns the position of a given search term within the string. You can learn more in MediaWiki\'s <a href="https://www.mediawiki.org/wiki/Module:String">documentation page</a>',
	],
	'wgAllowDisplayTitle' => [
		'name' => 'Allow Display Title',
		'restricted' => false,
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Allows use of {{DISPLAYTITLE}} magic word.',
	],
	'wgRestrictDisplayTitle' => [
		'name' => 'Restrict Display Title',
		'restricted' => false,
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Restrict {{DISPLAYTITLE}} to titles that normalize to the same canonical database key. Wikis with NoTitle extension installed have this config unset.',
	],
	'wgDisplayTitleHideSubtitle' => [
		'name' => 'Don\'t display the page\'s original title below the display title',
		'restricted' => false,
		'from' => 'displaytitle',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Set this to hide the page\'s original title as a subtitle below the title bar, shown by the Display Title extension.',
	],
	'wgCapitalLinks' => [
		'name' => 'Capital Links',
		'restricted' => false,
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Unset this to avoid forcing the first letter of links to capitals.',
	],
	'wgEnableCanonicalServerLink' => [
		'name' => 'Enable Canonical Server Link',
		'restricted' => false,
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Output a <link rel="canonical"> tag on every page indicating the canonical server which should be used, i.e. $wgServer or $wgCanonicalServer.',
	],
	'wgPageCreationLog' => [
		'name' => 'Page Creation Log',
		'restricted' => false,
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Whether to maintain a log of new page creations, which can be viewed at Special:Log/create.',
	],
	'wgMSCS_WarnNoCategories' => [
		'name' => 'MsCatSelect warn no categories',
		'restricted' => false,
		'from' => 'mscatselect',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'By default, if you try to save a page that has no categories assigned, MsCatSelect will ask for confirmation. If you wish to avoid this, unset this option.',
	],
	'wgCodeEditorEnableCore' => [
		'name' => 'CodeEditor Enable Core',
		'restricted' => false,
		'from' => 'codeeditor',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'To disable the editor on JavaScript and CSS pages in the MediaWiki, User and other core namespaces, unset this option.',
	],
	'wgScribuntoUseCodeEditor' => [
		'name' => 'Scribunto Use CodeEditor',
		'restricted' => false,
		'from' => 'codeeditor',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Set this to use it when editing Module pages.',
	],
	'wgScribuntoUseGeSHi' => [
		'name' => 'Scribunto Use GeSHi (SyntaxHighlight_GeSHi)',
		'restricted' => false,
		'from' => 'syntaxhighlight_geshi',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Use SyntaxHighlight_GeSHi extension to highlight syntax.',
	],
	'wgCategoryTreeDefaultMode' => [
		'name' => 'Category Tree Default Mode',
		'from' => 'categorytree',
		'restricted' => false,
		'type' => 'list',
		'overridedefault' => 0,
		'section' => 'edit',
		'help' => 'the default mode to use when no mode attribute is specified in a <categorytree> tag. You also need to set "Category Tree Category Page Mode" if you select the page mode.',
		'options' => [
			'Category' => 0,
			'Pages' => 10,
			'All' => 20,
			'Parents' => 100,
		],
	],
	'wgCategoryTreeCategoryPageMode' => [
		'name' => 'Category Tree Category Page Mode',
		'from' => 'categorytree',
		'restricted' => false,
		'type' => 'list',
		'overridedefault' => 0,
		'section' => 'edit',
		'help' => 'The mode to use when rendering trees on category pages.',
		'options' => [
			'Category' => 0,
			'Pages' => 10,
			'All' => 20,
			'Parents' => 100,
		],
	],
	'wgRandomGameDisplay' => [
		'name' => 'Random Game Display',
		'from' => 'randomgameunit',
		'restricted' => false,
		'type' => 'list-multi-bool',
		'allopts' => [
			'random_poll',
			'random_picturegame',
			'random_quiz',
		],
		'options' => [
			'Poll' => 'random_poll',
			'PictureGame' => 'random_picturegame',
			'Quiz' => 'random_quiz',
		],
		'overridedefault' => [
			'random_picturegame' => false,
			'random_poll' => false,
			'random_quiz' => false,
		],
		'section' => 'edit',
		'help' => 'Controls what games are enabled.',
	],
	'wgUserBoard' => [
		'name' => 'User Board',
		'restricted' => false,
		'from' => 'socialprofile',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Displays UserBoard-related things on social profile pages.',
	],
	'wgUserProfileDisplay' => [
		'name' => 'User Profile Display',
		'from' => 'socialprofile',
		'restricted' => false,
		'type' => 'list-multi-bool',
		'allopts' => [
			'activity',
			'articles',
			'avatar',
			'awards',
			'board',
			'custom',
			'foes',
			'friends',
			'games',
			'gifts',
			'interests',
			'personal',
			'profile',
			'stats',
			'userboxes',
		],
		'options' => [
			'Activity' => 'activity',
			'Articles' => 'articles',
			'Avatar' => 'avatar',
			'Awards' => 'awards',
			'Board' => 'board',
			'Custom' => 'custom',
			'Foes' => 'foes',
			'Friends' => 'friends',
			'Games' => 'games',
			'Gifts' => 'gifts',
			'Interests' => 'interests',
			'Personal' => 'personal',
			'Profile' => 'profile',
			'Stats' => 'stats',
			'Userboxes' => 'userboxes',
		],
		'overridedefault' => [
			'activity' => false,
			'articles' => true,
			'avatar' => true,
			'awards' => true,
			'board' => false,
			'custom' => true,
			'foes' => false,
			'friends' => false,
			'games' => false,
			'gifts' => true,
			'interests' => true,
			'personal' => true,
			'profile' => true,
			'stats' => false,
			'userboxes' => false,
		],
		'section' => 'edit',
		'help' => 'Enables default stuff to display on social profile pages by default',
	],
	'wgWikiForumAllowAnonymous' => [
		'name' => 'WikiForum Allow Anonymous',
		'from' => 'wikiforum',
		'type' => 'check',
		'restricted' => false,
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Allow Anonymous (users who are not logged in) to use WikiForum',
	],
	'egApprovedRevsAutomaticApprovals' => [
		'name' => 'Automatically approve new revisions',
		'from' => 'approvedrevs',
		'type' => 'check',
		'restricted' => false,
		'overridedefault' => true,
		'section' => 'edit',
		'help' => 'Uncheck this box to require new revisions to be manually approved even if made by an administrator',
	],
	'wgTwitterCardType' => [
		'name' => 'Twitter Card Type (WikiSEO)',
		'from' => 'wikiseo',
		'restricted' => false,
		'type' => 'list',
		'overridedefault' => 'summery_large_image',
		'section' => 'edit',
		'help' => 'Type of twitter card to use.',
		'options' => [
			'Summary' => 'summary',
			'Summary large image' => 'summary_large_image',
		],
	],
	'wgGoogleSiteVerificationKey' => [
		'name' => 'Google Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Site verification key for Google Search Console.',
	],
	'wgBingSiteVerificationKey' => [
		'name' => 'Bing Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Site verification key for Bing Webmaster Center.',
	],
	'wgFacebookAppId' => [
		'name' => 'Facebook App Id (WikiSEO)',
		'from' => 'wikiseo',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'App Id for Facebook Insights.',
	],
	'wgYandexSiteVerificationKey' => [
		'name' => 'Yandex Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Site verification key for Yandex Webmasters.',
	],
	'wgAlexaSiteVerificationKey' => [
		'name' => 'Alexa Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Site verification key for Alexa Console.',
	],
	'wgPinterestSiteVerificationKey' => [
		'name' => 'Pinterest Site Verification Key (WikiSEO)',
		'from' => 'wikiseo',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'edit',
		'help' => 'Site verification key for Pinterest Console.',
	],
	// Links
	'wgExternalLinkTarget' => [
		'name' => 'External Link Target',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'Blank' => '_blank',
			'Default' => false,
		],
		'overridedefault' => false,
		'section' => 'links',
		'help' => 'Set a default target for external links.',
	],
	'wgRottenLinksCurlTimeout' => [
		'name' => 'RottenLinks Timeout Threshold',
		'restricted' => false,
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 5,
		'maxint' => 120,
		'overridedefault' => 10,
		'section' => 'links',
		'help' => 'Number of seconds before a RottenLinks request returns no response. Min: 5. Max: 120.'
	],

	// Localisation (E.G i18n/timezone etc)
	'wgLocaltimezone' => [
		'name' => 'Timezone',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'timezone',
		'overridedefault' => 'UTC',
		'section' => 'localisation',
		'help' => 'This will adapt your wikis time over clock to whatever timezone you choose for all users, however it can be changed through user\'s preferences.',
	],
	'wgTranslateDocumentationLanguageCode' => [
		'name' => 'Translate Documentation Language Code',
		'from' => 'translate',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'info' => 'info',
			'No Documentation' => false,
			'qqq' => 'qqq',
		],
		'overridedefault' => false,
		'section' => 'localisation',
		'help' => 'Language code for message documentation.',
	],
	'wgULSAnonCanChangeLanguage' => [
		'name' => 'Allow anonymous users to change language',
		'from' => 'universallanguageselector',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'localisation',
		'help' => 'Enabling allows anonymous users to control the language they view the wiki in.',
	],
	'wgPageLanguageUseDB' => [
		'name' => 'Enable per page language',
		'restricted' => false,
		'from' => 'mediawiki',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'localisation',
		'help' => 'Allows to change the page language for MediaWiki pages.',
	],
	'wmgUseYandexTranslate' => [
		'name' => 'Use Yandex Machine Translation on Special:Translate',
		'from' => 'translate',
		'restricted' => 'false',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'localisation',
		'help' => 'Adds suggestions from Yandex to Special:Translate',
	],
	// Maps (E.G navigation)
	'wgKartographerWikivoyageMode' => [
		'name' => 'Kartographer Wikivoyage Mode',
		'restricted' => false,
		'from' => 'kartographer',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'maps',
		'help' => 'Enables Wikivoyage mode.',
	],
	'wgKartographerUseMarkerStyle' => [
		'name' => 'Kartographer Use Marker Style',
		'restricted' => false,
		'from' => 'kartographer',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'maps',
		'help' => 'Allows Kartographer to extract CSS style to be used by the link from the GeoJSON.',
	],

	// Media/File
	'wgEnableUploads' => [
		'name' => 'Enable File Uploads',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'Check or uncheck this option if you want to enable or disable the upload of files on your wiki.',
	],
	'wgAllowCopyUploads' => [
		'name' => 'Enable File Uploads Through URL',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'By default Miraheze enables file upload only from a local media but with this option you can upload files remotely from other sites.',
	],
	'wgCopyUploadsFromSpecialUpload' => [
		'name' => 'Enable File Uploads Through URL on Special:Upload',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'This option adds a textbox on Special:Upload enabling you to upload files from any URL.',
	],
	'wgUseInstantCommons' => [
		'name' => 'Enable Wikimedia Commons Files',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'This option allows you to use the WikiMedia Commons file database on your wiki.',
	],
	'wgMirahezeCommons' => [
		'name' => 'Enable Miraheze Commons (linking to commons.miraheze.org)',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'This option allows you to use the Miraheze Commons file database on your wiki.',
	],
	'wgShowArchiveThumbnails' => [
		'name' => 'Show Old Thumbnails On Description Page',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'Whether to show thumbnails for old images on the image\'s description page.',
	],
	'wgAllowExternalImages' => [
		'name' => 'Allow External Images',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'Determines whether or not MediaWiki will allow external images to be rendered inline with text',
	],
	'wgAllowImageTag' => [
		'name' => 'Allow Image Tag',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'Allow img tag to be used in wikitext.',
	],
	'wgSVGConverter' => [
		'name' => 'SVG Converter',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'Inkscape' => 'inkscape',
			'ImageMagick' => 'ImageMagick',
		],
		'overridedefault' => 'ImageMagick',
		'section' => 'media',
		'help' => 'This picks the converter to convert Scalable Vector Graphics (SVG) to PNG. You may want to choose Inkscape if your SVG->PNG conversion results in a black image.',
	],
	'wgMediaViewerEnableByDefault' => [
		'name' => 'MediaViewer Enable By Default',
		'from' => 'multimediaviewer',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'This enables MediaViewer for everyone.',
	],
	'wgMSU_checkAutoCat' => [
		'name' => 'MsUpload check auto cat',
		'from' => 'msupload',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'If set, sets the checkbox for adding a category to a page by default.',
	],
	'wgMSU_confirmReplace' => [
		'name' => 'MsUpload confirm replace',
		'from' => 'msupload',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'If set, shows the "Replace file" checkbox.',
	],
	'wgMSU_showAutoCat' => [
		'name' => 'MsUpload show auto cat',
		'from' => 'msupload',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'If set, files uploaded while editing a category page will be added to that category.',
	],
	'wgMSU_useDragDrop' => [
		'name' => 'MsUpload use drag and drop',
		'from' => 'msupload',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'media',
		'help' => 'If set, the drag & drop area will be shown.',
	],
	'wgMaxImageArea' => [
		'name' => 'Max Image Area',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '1.25e7',
		'section' => 'media',
		'help' => 'Specifies the max pixels you can have in a image.',
	],
	'wgCommonsMetadataForceRecalculate' => [
		'name' => 'Force Remote Image Description Parsing',
		'from' => 'commonsmetadata',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'media',
		'help' => 'Set this to true to force CommonsMetadata to parse the description page of the image and extract the metadata when using images from other wikis.'
	],

	// Notifications
	'wgCookieWarningMoreUrl' => [
		'name' => 'CookieWarning More Url',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => 'https://meta.miraheze.org/wiki/Privacy_Policy#4._Cookies',
		'section' => 'notifications',
		'help' => 'Set the URL to your \'More Information\' page.',
	],
	'wgUsersNotifiedOnAllChanges' => [
		'name' => 'Users Notified On All Changes',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'users',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'Array of usernames who will be sent a notification email for every change which occurs on a wiki.',
	],	
	'wgEchoCrossWikiNotifications' => [
		'name' => 'Echo Cross Wiki Notifications',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Whether to enable the cross-wiki notifications feature.',
	],
	'wgEchoMentionStatusNotifications' => [
		'name' => 'Echo Mention Status Notifications',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Enable mention success/failure notifications.',
	],
	'wmgSiteNoticeOptOut' => [
		'name' => 'Opt out of global Miraheze notices',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'Opts your wiki out of global Miraheze notices, only showing important notices.',
	],
	'wgMinervaEnableSiteNotice' => [
		'name' => 'Minerva Sitenotice',
		'from' => 'mobilefrontend',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Display the Sitenotice on the Minerva skin.',
	],
	'wgModerationNotificationEnable' => [
		'name' => 'Moderation Notification Enable',
		'from' => 'moderation',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'If set, notification email will be sent to "Moderation Email" each time an edit is queued for moderation.',
	],
	'wgModerationNotificationNewOnly' => [
		'name' => 'Moderation Notification New Only',
		'from' => 'moderation',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'If set, only notify about new pages (but not about edits in existing pages).',
	],
	'wgDismissableSiteNoticeForAnons' => [
		'name' => 'Dismissable Site Notice For Anons',
		'from' => 'dismissablesitenotice',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'This allows to set whether or not it should be possible for anonymous visitors of the wiki to dismiss the site notice shown.',
	],
	'wgDiscordNotificationBlockedUser' => [
		'name' => 'Discord Notification Blocked User',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Notify on user or IP blocked in MediaWiki.',
	],
	'wgDiscordNotificationNewUser' => [
		'name' => 'Discord Notification New User',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'notifications',
		'help' => 'Notify on new user added into MediaWiki.',
	],
	'wgHAWelcomeStaffGroupName' => [
		'name' => 'HAWelcome Staff Group Name',
		'from' => 'hawelcome',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => 'sysop',
		'section' => 'notifications',
		'help' => 'The name of the group that can serve as a fallback when no sysops have been active in the last 60 days.',
	],
	'wgHAWelcomeSignatureFromPreferences' => [
		'name' => 'HAWelcome Signature From Preferences',
		'from' => 'hawelcome',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'notifications',
		'help' => 'This configuration variable toggles if the signature of the welcomer should be the one they have set in their preferences.',
	],

	// Recent changes
	'wgRCMaxAge' => [
		'name' => 'RecentChanges max age',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'integer',
		'minint' => 1,
		'maxint' => 15552000,
		'overridedefault' => 180 * 24 * 3600,
		'section' => 'recentchanges',
		'help' => 'Items in the recentchanges table are periodically purged; entries older than this many seconds will go.',
	],
	'wgRCLinkDays' => [
		'name' => 'RecentChanges link days',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'list-multi',
		'options' => [
			'1 (86400 seconds)' => 1,
			'3 (259200 seconds)' => 3,
			'7 (604800 seconds)' => 7,
			'14 (1209600 seconds)' => 14,
			'30 (2592000 seconds)' => 30,
			'60 (5184000 seconds)' => 60,
			'90 (7776000 seconds)' => 90,
			'180 (15552000 seconds)' => 180,
		],
		'overridedefault' => [
			1,
			3,
			7,
			14,
			30,
		],
		'section' => 'recentchanges',
		'help' => 'List days options to list in the Special:Recentchanges and Special:Recentchangeslinked pages.',
	],
	'wgCommentsInRecentChanges' => [
		'name' => 'Enable Comments In RecentChanges',
		'from' => 'comments',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'recentchanges',
		'help' => 'Shows comments in the RecentChanges special page.',
	],
	'wgWikiForumLogsInRC' => [
		'name' => 'Display WikiForum logs in RecentChanges',
		'from' => 'wikiforum',
		'type' => 'check',
		'restricted' => false,
		'overridedefault' => true,
		'section' => 'recentchanges',
		'help' => 'Toggles the display of WikiForum logs in Special:RecentChanges',
	],
	'wgRCWatchCategoryMembership' => [
		'name' => 'Treat Category Membership as a RecentChange',
		'from' => 'mediawiki',
		'type' => 'check',
		'restricted' => false,
		'overridedefault' => false,
		'section' => 'recentchanges',
		'help' => 'Shows changes to category membership as an action in Special:RecentChanges',
	],
	'wgSimpleChangesOnlyContentNamespaces' => [
		'name' => 'Display only content namespaces for Simple Changes',
		'from' => 'simplechanges',
		'type' => 'check',
		'restricted' => false,
		'overridedefault' => false,
		'section' => 'recentchanges',
		'help' => 'Restricts the list to display only content namespaces',
	],
	'wgSimpleChangesOnlyLatest' => [
		'name' => 'Prevent duplicate titles appearing for Simple Changes',
		'from' => 'simplechanges',
		'type' => 'check',
		'restricted' => false,
		'overridedefault' => true,
		'section' => 'recentchanges',
		'help' => 'Avoids duplicate titles showing up in the list by only showing changes that match each page&apos;s most recent revision',
	],
	'wgSimpleChangesShowUser' => [
		'name' => 'Display the user name of the user who made the change for Simple Changes',
		'from' => 'simplechanges',
		'type' => 'check',
		'restricted' => false,
		'overridedefault' => false,
		'section' => 'recentchanges',
		'help' => 'Shows the user name of the user who made the change',
	],

	// Restricted (where settings that are restricted go)
	'wgDefaultRobotPolicy' => [
		'name' => 'Default Robot Policy',
		'from' => 'mediawiki',
		'restricted' => true,
		'type' => 'text',
		'overridedefault' => 'index,follow',
		'section' => 'restricted',
		'help' => 'Allows specifying the default robot policy for all pages on the wiki.',
	],
	'wgModerationEmail' => [
		'name' => 'Moderation Email',
		'from' => 'moderation',
		'restricted' => true,
		'type' => 'text',
		// Must match wgPasswordSender from LocalSettings.php
		'overridedefault' => 'noreply@miraheze.org',
		'section' => 'restricted',
		'help' => 'Sets the email for notifications to go to.',
	],
	'wgAccountCreationThrottle' => [
		'name' => 'Account Creation Throttle',
		'from' => 'mediawiki',
		'restricted' => true,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 900000000,
		'overridedefault' => 5,
		'section' => 'restricted',
		'help' => 'Number of accounts each IP address may create, 0 to disable.',
	],
	'wgSVGMetadataCutoff' => [
		'name' => 'SVG Metadata Cutoff',
		'from' => 'mediawiki',
		'restricted' => true,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 90000000,
		'overridedefault' => 262144,
		'section' => 'restricted',
		'help' => 'Don\'t read SVG metadata beyond this point.',
	],
	// If necessary we can increase maxint.
	'wgMaxArticleSize' => [
		'name' => 'Max Article Size',
		'from' => 'mediawiki',
		'restricted' => true,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 10000,
		'overridedefault' => 2048,
		'section' => 'restricted',
		'help' => 'Maximum page size in kilobytes.',
	],
	'wgDisqusShortname' => [
		'name' => 'Disqus Shortname',
		'from' => 'mediawiki',
		'restricted' => true,
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'restricted',
		'help' => 'The Disqus shortname for your site. This is the identifier (or the hostname) you specify when entering your unique Disqus URL. This is required when using the DisqusTag extension.',
	],
	'wgPageDisqusShortname' => [
		'name' => 'Page DisqusShortname',
		'from' => 'mediawiki',
		'restricted' => true,
		'type' => 'text',
		'overridedefault' => false,
		'section' => 'restricted',
		'help' => 'The Disqus shortname for your site. This is the identifier (or the hostname) you specify when entering your unique Disqus URL. This is required when using the PageDisqus extension.',
	],
	'wgMaxCredits' => [
		'name' => 'Editing attribution',
		'from' => 'mediawiki',
		'restricted' => true,
		'type' => 'integer',
		'minint' => -1,
		'maxint' => 25,
		'overridedefault' => 0,
		'section' => 'restricted',
		'help' => 'Number of editors to attribute.',
	],
	'wgHAWelcomeWelcomeUsername' => [
		'name' => 'HAWelcome Welcome Username',
		'from' => 'hawelcome',
		'restricted' => true,
		'type' => 'text',
		'overridedefault' => $wgSitename,
		'section' => 'restricted',
		'help' => 'This configuration variable contains the name of the user that should leave the welcome message. If this user is flagged as a bot, the edits will be marked as a bot edit.',
	],
	// Default list must be kept insync with wgFileExtensions in LocalSettings.php
	'wgFileExtensions' => [
		'name' => 'File Extensions',
		'from' => 'mediawiki',
		'restricted' => true,
		'type' => 'list-multi',
		'options' => [
			'add' => 'add',
			'alist' => 'alist',
			'apk' => 'apk',
			'apng' => 'apng',
			'asv' => 'asv',
			'avi' => 'avi',
			'bat' => 'bat',
			'bib' => 'bib',
			'bmp' => 'bmp',
			'bnk' => 'bnk',
			'bst' => 'bst',
			'bz' => 'bz',
			'bz2' => 'bz2',
			'c' => 'c',
			'cap' => 'cap',
			'chr' => 'chr',
			'cls' => 'cls',
			'cpp' => 'cpp',
			'crt' => 'crt',
			'css' => 'css',
			'dae' => 'dae',
			'dat' => 'dat',
			'data' => 'data',
			'desktop' => 'desktop',
			'dia' => 'dia',
			'djvu' => 'djvu',
			'doc' => 'doc',
			'docx' => 'docx',
			'eot' => 'eot',
			'exe' => 'exe',
			'fig' => 'fig',
			'fla' => 'fla',
			'flac' => 'flac',
			'fpd' => 'fpd',
			'gb' => 'gb',
			'gba' => 'gba',
			'gbc' => 'gbc',
			'gbs' => 'gbs',
			'gif' => 'gif',
			'gp' => 'gp',
			'gz' => 'gz',
			'gz2' => 'gz2',
			'h' => 'h',
			'hes' => 'hes',
			'hpp' => 'hpp',
			'htm' => 'htm',
			'html' => 'html',
			'hxx' => 'hxx',
			'ico' => 'ico',
			'ini' => 'ini',
			'ipe' => 'ipe',
			'ips' => 'ips',
			'jpeg' => 'jpeg',
			'jpg' => 'jpg',
			'js' => 'js',
			'lua' => 'lua',
			'm4a' => 'm4a',
			'mat' => 'mat',
			'mbz' => 'mbz',
			'md' => 'md',
			'mhtml' => 'mhtml',
			'mid' => 'mid',
			'midi' => 'midi',
			'mkv' => 'mkv',
			'mov' => 'mov',
			'mp3' => 'mp3',
			'mp4' => 'mp4',
			'mus' => 'mus',
			'naf' => 'naf',
			'nes' => 'nes',
			'nsf' => 'nsf',
			'odg' => 'odg',
			'odp' => 'odp',
			'ods' => 'ods',
			'odt' => 'odt',
			'off' => 'off',
			'oga' => 'oga',
			'ogg' => 'ogg',
			'ogv' => 'ogv',
			'ogx' => 'ogx',
			'opus' => 'opus',
			'otf' => 'otf',
			'otg' => 'otg',
			'pcap' => 'pcap',
			'pdf' => 'pdf',
			'perf' => 'perf',
			'php' => 'php',
			'plot' => 'plot',
			'png' => 'png',
			'pps' => 'pps',
			'ppt' => 'ppt',
			'pptx' => 'pptx',
			'psd' => 'psd',
			'pub' => 'pub',
			'py' => 'py',
			'rar' => 'rar',
			'rtf' => 'rtf',
			'scss' => 'scss',
			'sfnt' => 'sfnt',
			'sh' => 'sh',
			'smc' => 'smc',
			'spc' => 'spc',
			'spl' => 'spl',
			'stl' => 'stl',
			'sty' => 'sty',
			'svg' => 'svg',
			'swf' => 'swf',
			'tar' => 'tar',
			'tar.gz' => 'tar.gz',
			'tex' => 'tex',
			'tif' => 'tif',
			'tiff' => 'tiff',
			'ttf' => 'ttf',
			'txt' => 'txt',
			'val' => 'val',
			'vit' => 'vit',
			'vsd' => 'vsd',
			'vst' => 'vst',
			'wav' => 'wav',
			'webm' => 'webm',
			'webp' => 'webp',
			'wma' => 'wma',
			'wmv' => 'wmv',
			'woff' => 'woff',
			'woff2' => 'woff2',
			'xcf' => 'xcf',
			'xhtml' => 'xhtml',
			'xls' => 'xls',
			'xlsx' => 'xlsx',
			'xlxs' => 'xlxs',
			'xml' => 'xml',
			'xps' => 'xps',
			'zip' => 'zip',
			'7z' => '7z',
		],
		'overridedefault' => [
			'djvu',
			'gif',
			'ico',
			'jpg',
			'jpeg',
			'ogg',
			'pdf',
			'png',
			'svg',
		],
		'section' => 'restricted',
		'help' => 'This is the list of preferred extensions for uploading files. Uploading files with extensions not selected in this list will trigger a warning.',
	],
	'wgExpensiveParserFunctionLimit' => [
		'name' => 'Expensive Parser Function Limit',
		'restricted' => true,
		'from' => 'mediawiki',
		'type' => 'integer',
		'minint' => 50,
		'maxint' => 500,
		'overridedefault' => 99,
		'section' => 'restricted',
		'help' => 'Number of expensive parser functions allowed on a single page. Min: 50. Max: 500.'
	],

	// Styling (E.G skins/logos etc)
	'wgDefaultSkin' => [
		'name' => 'Default Skin',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'skin',
		'options' => [],
		'overridedefault' => 'vector',
		'section' => 'styling',
		'help' => 'This change the visual interface to the selected skin for all users, however it can be changed through user\'s preferences.',
	],
	'wgLogo' => [
		'name' => 'Logo',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => "https://$wmgUploadHostname/metawiki/3/35/Miraheze_Logo.svg",
		'section' => 'styling',
		'help' => 'This will replace Miraheze\'s default logo. See <a href="https://meta.miraheze.org/wiki/ManageWiki#How_do_I_change_my_logo.2Ffavicon.3F">this link</a> for how you can change it. Also sets the value of <code>$wgLogos[\'1x\']</code>.',
	],
	'wgFavicon' => [
		'name' => 'Favicon',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '/favicon.ico',
		'section' => 'styling',
		'help' => 'A favicon is a shortcut image that is displayed on your visitor\'s browser address bar and in the bookmarks page. Most often it is a smaller version of the logo. See <a href="https://meta.miraheze.org/wiki/ManageWiki#How_do_I_change_my_logo.2Ffavicon.3F">this link</a> for how you can add one.',
	],
	'wgAppleTouchIcon' => [
		'name' => 'Apple Touch Icon',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '/apple-touch-icon.png',
		'section' => 'styling',
		'help' => 'Favicon for Apple mobile devices. See <a href="https://meta.miraheze.org/wiki/ManageWiki#How_do_I_change_my_logo.2Ffavicon.3F">this link</a> on how you can add one.',
	],
	'wgWordmark' => [
		'name' => 'Wordmark',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'url',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'This will set the value of <code>$wgLogos[\'wordmark\'][\'src\']</code>. Also used as the copyright wordmark for the Minerva skin.',
	],
	'wgWordmarkWidth' => [
		'name' => 'Wordmark Width',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 9999,
		'overridedefault' => 116,
		'section' => 'styling',
		'help' => 'This will set the width value of the wordmark set by <code>$wgWordmark</code>. For use with the Minerva skin\'s copyright wordmark, this should be set to "116"',
	],
	'wgWordmarkHeight' => [
		'name' => 'Wordmark Height',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 9999,
		'overridedefault' => 18,
		'section' => 'styling',
		'help' => 'This will set the height value of the wordmark set by <code>$wgWordmark</code>. For use with the Minerva skin\'s copyright wordmark, this should be set to "18"',
	],
	'wmgWikiapiaryFooterPageName' => [
		'name' => 'Wikiapiary Footer Page Name',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'text',
		'overridedefault' => '',
		'section' => 'styling',
		'help' => 'Set to your wiki\'s page name at <a href="https://www.wikiapiary.com">Wikiapiary</a> to add the monitored by Wikiapary footer icon. If you do not have an article there for your wiki, please leave this field blank.',
	],
	'wgMetrolookDownArrow' => [
		'name' => 'Metrolook Down Arrow',
		'from' => 'metrolook',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'This configuration variable has to be true for the tiles to be generated.',
	],
	'wgMetrolookUploadButton' => [
		'name' => 'Metrolook Upload Button',
		'from' => 'metrolook',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'When enabled, an "Upload file" link is generated in the top menu bar, before the content-specific action links ("History", "Discussion", etc.)',
	],
	'wgMetrolookBartile' => [
		'name' => 'Metrolook Bartile',
		'from' => 'metrolook',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'When "Metrolook Down Arrow" is enabled and "Metrolook Bartile" is enabled, the tile menu will be generated from <a href="/wiki/MediaWiki:Metrolook-tiles">MediaWiki:Metrolook-tiles</a>. If "Metrolook Down Arrow" is not set and "Metrolook Bartile" is not set, then the tile menu will be generated from <a href="/wiki/MediaWiki:Metrolook-tiles-second">MediaWiki:Metrolook-tiles-second</a>.',
	],
	'wgMetrolookMobile' => [
		'name' => 'Metrolook Mobile',
		'from' => 'metrolook',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'When enabled, makes the UI responsive on mobiles.',
	],
	'wgMetrolookUseIconWatch' => [
		'name' => 'Metrolook Use Icon Watch',
		'from' => 'metrolook',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'When enabled, it uses an icon for the watch/unwatch button.',
	],
	'wgMetrolookLine' => [
		'name' => 'Metrolook Line',
		'from' => 'metrolook',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'If not set, then the img.line element (white divider line in the top menu, between the site name and the down arrow/"Upload file" link) won\'t be generated.',
	],
	'wgRelatedArticlesFooterWhitelistedSkins' => [
		'name' => 'RelatedArticles Footer Whitelisted Skins',
		'from' => 'relatedarticles',
		'restricted' => false,
		'type' => 'skins',
		'options' => [],
		'overridedefault' => [
			'minerva',
			'timeless',
			'vector'
		],
		'section' => 'styling',
		'help' => 'List of skin names (e.g. "minerva", "vector") where related articles will be shown in the footer.',
	],
	'wgMultiBoilerplateDiplaySpecialPage' => [
		'name' => 'MultiBoilerplate Diplay SpecialPage',
		'from' => 'multiboilerplate',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'if set, will add to the wiki a page named Special:Boilerplates that shows the currently configured boilerplates.',
	],
	'wgAllowUserCss' => [
		'name' => 'Allow User Css',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'Allow user Cascading Style Sheets (CSS). For example User:<user>/*.css.',
	],
	'wgAllowUserJs' => [
		'name' => 'Allow User Js',
		'from' => 'mediawiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'styling',
		'help' => 'Allow user JavaScript pages. For example User:<user>/*.js.',
	],
	'wgDefaultTheme' => [
		'name' => 'Default Theme',
		'from' => 'theme',
		'restricted' => false,
		'type' => 'list',
		'options' => [
			'Default' => 'default',
			'Dark (Monobook and Vector only)' => 'dark',
			'Deepsea (Vector only)' => 'deepsea',
			'Pink (Monobook only)' => 'pink',
			'Stellarbook (Monobook only)' => 'stellarbook',
		],
		'overridedefault' => 'default',
		'section' => 'styling',
		'help' => 'Sets which theme is displayed by default when users visit your wiki.',
	],
	'wgManageWikiForceSidebarLinks' => [
		'name' => 'Force ManageWiki side bar links',
		'from' => 'managewiki',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'Force the display of ManageWiki links in the sidebar for all users. The link text will differ for nonprivileged users.',
	],
	'wmgShowPopupsByDefault' => [
		'name' => 'Show Popups by default',
		'from' => 'popups',
		'restricted' => false,
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'styling',
		'help' => 'When enabled, this shows Popups by default.',
	],

	// Wikibase
	'wmgWikibaseRepoUrl' => [
		'name' => 'Repository URL',
		'restricted' => false,
		'from' => 'wikibaseclient',
		'type' => 'url',
		'overridedefault' => 'https://wikidata.org',
		'section' => 'wikibase',
		'help' => 'URL of the Wikibase repository the client should connect to.'
	],
	'wmgWikibaseRepoDatabase' => [
		'name' => 'Repository Database',
		'restricted' => false,
		'from' => 'wikibaseclient',
		'type' => 'databases',
		'overridedefault' => $wi->dbname,
		'section' => 'wikibase',
		'help' => 'Database identifier of the repository being used. If unknown, select the identifier for this wiki.'
	],
	'wmgAllowEntityImport' => [
		'name' => 'Allow Entity Import',
		'restricted' => false,
		'from' => 'wikibaserepository',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'wikibase',
		'help' => 'Allow importing entities via Special:Import and importDump.php.',
	],
	'wmgEnableEntitySearchUI' => [
		'name' => 'Enable Entity Search UI',
		'restricted' => false,
		'from' => 'wikibaserepository',
		'type' => 'check',
		'overridedefault' => true,
		'section' => 'wikibase',
		'help' => 'To determine if entity search UI should be enabled or not.',
	],
	'wmgFederatedPropertiesEnabled' => [
		'name' => 'Enable Federated Properties',
		'restricted' => false,
		'from' => 'wikibaserepository',
		'type' => 'check',
		'overridedefault' => false,
		'section' => 'wikibase',
		'help' => 'To determine if federated properties should be enabled or not.',
	],
	'wmgWikibaseItemNamespaceID' => [
		'name' => 'Item Namespace ID',
		'from' => 'wikibaseclient',
		'restricted' => false,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 9999,
		'overridedefault' => 0,
		'section' => 'wikibase',
		'help' => 'Namespace ID of the Item namespace on the upstream Wikibase installation. Leave as-is if unsure.',
	],
	'wmgWikibasePropertyNamespaceID' => [
		'name' => 'Property Namespace ID',
		'from' => 'wikibaseclient',
		'restricted' => false,
		'type' => 'integer',
		'minint' => 0,
		'maxint' => 9999,
		'overridedefault' => 120,
		'section' => 'wikibase',
		'help' => 'Namespace ID of the Property namespace on the upstream Wikibase installation. Leave as-is if unsure.',
	]
];
