<?php

define( 'MW_NO_SESSION', 1 );
define( 'MW_ENTRY_POINT', 'robots' );

require_once '/srv/mediawiki/config/initialise/MirahezeFunctions.php';
require MirahezeFunctions::getMediaWiki( 'includes/WebStart.php' );

use MediaWiki\Content\TextContent;
use MediaWiki\MediaWikiServices;
use MediaWiki\SpecialPage\SpecialPage;
use MediaWiki\Title\Title;

/**
 * Disallow lines for the localized/percent-decoded Special: page prefixes.
 * Mostly needed for Special:CentralAutoLogin.
 */
function wfRobotsGetSpecialPageRules(): array {
	$specialPagePath = SpecialPage::getTitleFor( 'DOESNOTEXIST' )->getLocalURL();
	$specialPrefix = substr( $specialPagePath, 0, strpos( $specialPagePath, 'DOESNOTEXIST' ) );

	// Some robots.txt parsers don't like the percent-encoded form
	$prefix2 = rawurldecode( $specialPrefix );
	if ( $specialPrefix === $prefix2 ) {
		$prefixes = [ $specialPrefix ];
	} else {
		$prefixes = [ $specialPrefix, $prefix2 ];
	}

	$lines = [];
	foreach ( $prefixes as $prefix ) {
		$lines[] = "Disallow: $prefix";
		// Handle the other URL pattern in case article root changes
		if ( str_starts_with( $prefix, '/wiki/' ) ) {
			$newPrefix = str_replace( '/wiki/', '/', $prefix );
		} else {
			$newPrefix = '/wiki' . $prefix;
		}
		$lines[] = "Disallow: $newPrefix";
	}
	return $lines;
}

/**
 * Rules that apply to all crawlers (User-agent: *).
 * Reused verbatim for bots that should also respect these rules (e.g. bingbot).
 */
function wfRobotsGetDefaultRules(): array {
	return array_merge( [
		'Allow: /w/api.php?action=mobileview&',
		'Allow: /w/load.php?',
		'Disallow: /w/',
		'Disallow: /geoip',
		'Disallow: /rest_v1/',
		# All action pages and veaction
		'Disallow: /*?action=',
		'Disallow: /*?*&action=',
		'Disallow: /*?veaction=',
		'Disallow: /*?*&veaction=',
		# Diffs and permalinks
		'Disallow: /*?diff=',
		'Disallow: /*?*&diff=',
		'Disallow: /*?curid=',
		'Disallow: /*?*&curid=',
		'Disallow: /*?oldid=',
		'Disallow: /*?*&oldid=',
		'Disallow: /*?curid=',
		'Disallow: /*?*&curid=',
		# Special pages in English
		'Disallow: /wiki/Special:',
		'Disallow: /Special:',
		# Mostly for Special:CentralAutoLogin
		'Disallow: /metawiki/wiki/Special:',
	], wfRobotsGetSpecialPageRules() );
}

function wfRobotsEmitGroup( string $userAgent, array $lines ): void {
	echo "User-agent: $userAgent\n";
	// Remove duplicate rules
	$lines = array_unique( $lines );
	foreach ( $lines as $line ) {
		echo "$line\n";
	}
	echo "\n";
}

header( 'Content-Type: text/plain; charset=utf-8' );
header( 'Vary: X-Subdomain' );
header( 'Cache-Control: s-maxage=3600, must-revalidate, max-age=0' );

$mtime = filemtime( __FILE__ );
$extraText = '';
$page = MediaWikiServices::getInstance()
	->getWikiPageFactory()
	->newFromTitle( Title::newFromText( 'Mediawiki:robots.txt' ) );
if ( $page->exists() ) {
	$content = $page->getContent();
	$extraText = ( $content instanceof TextContent ) ? $content->getText() : '';
	// Take last modified timestamp of page into account
	$mtime = max( $mtime, wfTimestamp( TS_UNIX, $page->getTouched() ) );
}

$lastmod = gmdate( 'D, j M Y H:i:s', $mtime ) . ' GMT';
header( "Last-modified: $lastmod" );

if ( php_uname( 'n' ) === 'test151' ) {
	echo "User-agent: *\nDisallow: /\n";
}

echo "# robots.txt for Miraheze, autogenerated by robots.php in the mw-config repository on GitHub.\n";
echo "# See the robots.php file for rationales and detailed comments.\n\n";

wfRobotsEmitGroup( '*', wfRobotsGetDefaultRules() );

$blockedBots = [
	'SemrushBot',
	'AhrefsBot',
	'Bytespider',
	'PetalBot',
	'DotBot',
	'MegaIndex',
	'serpstatbot',
	'Barkrowler',
	'SeekportBot',
];
foreach ( $blockedBots as $bot ) {
	wfRobotsEmitGroup( $bot, [ 'Disallow: /' ] );
}

# Keep Crawl-Delay rules at the bottom
# Bots that don't understand Crawl-Delay might break when encountering it
# See https://github.com/otwcode/otwarchive/pull/4411#discussion_r1044351129 (English) and https://webtan.impress.co.jp/e/2022/11/04/43611 (Japanese)

# Throttle BingBot (also respects the default disallow rules above)
wfRobotsEmitGroup( 'bingbot', array_merge( wfRobotsGetDefaultRules(), [ 'Crawl-delay: 20' ] ) );

wfRobotsEmitGroup( 'MJ12bot', [ 'Crawl-Delay: 10' ] );

# TODO: Crawl-delay is not respected since 2018
wfRobotsEmitGroup( 'YandexBot', [ 'Crawl-Delay: 2.5' ] );

# Dynamic sitemap url
echo "Sitemap: {$wgServer}/sitemap.xml" . "\n\n";

echo $extraText;
